-- 007_seed_bihar_hardware_catalogue.sql
-- Final clean product catalogue seed.
-- Source: bihar_hardware_bilingual_with_size_v9.csv
-- Product rows: 1,085
--
-- Product mapping:
--   Transliteration (Roman, with Size) -> products.name_en
--   Product Name (Local/Hindi, with Size) -> products.name_hi
--   Packing/Unit -> ignored
--   unit_id -> NULL
--   brand -> NULL
--
-- Existing category mapping:
--   Fasteners & Fixings       -> Fasteners
--   Building Materials        -> Building Materials
--   Hand Tools                -> Hand Tools
--   Power Tools               -> Power Tools
--   Plumbing & Sanitary       -> Plumbing
--   Architectural Hardware    -> Door Hardware
--   Electrical Goods          -> Electrical
--   Agricultural & Rural Tools -> Farmer/Agricultural Tools
--   Agricultural handpump rows -> Handpump (Chapakal) Parts
--   Paints & Adhesives        -> Paints / Adhesives based on product name
--   Safety & Misc Essentials  -> Safety Items / Measuring/Misc based on product name

BEGIN;

-- Replace the old product catalogue.
DELETE FROM products;

INSERT INTO products (
    name_en,
    name_hi,
    category_id,
    unit_id,
    brand,
    status
)
SELECT
    seed.name_en,
    seed.name_hi,
    c.id,
    NULL,
    NULL,
    'active'
FROM (
    VALUES
        ('Fasteners', 'Kati (0.5")', 'कटी (0.5")'),
        ('Fasteners', 'Kati (1")', 'कटी (1")'),
        ('Fasteners', 'Kati (1.5")', 'कटी (1.5")'),
        ('Fasteners', 'Kati (2")', 'कटी (2")'),
        ('Fasteners', 'Kati (2.5")', 'कटी (2.5")'),
        ('Fasteners', 'Kati (3")', 'कटी (3")'),
        ('Fasteners', 'Kati (4")', 'कटी (4")'),
        ('Fasteners', 'Kati (5")', 'कटी (5")'),
        ('Fasteners', 'Kati (6")', 'कटी (6")'),
        ('Fasteners', 'Dewal Kati (0.5")', 'दीवाल कटी (0.5")'),
        ('Fasteners', 'Dewal Kati (1")', 'दीवाल कटी (1")'),
        ('Fasteners', 'Dewal Kati (1.5")', 'दीवाल कटी (1.5")'),
        ('Fasteners', 'Dewal Kati (2")', 'दीवाल कटी (2")'),
        ('Fasteners', 'Dewal Kati (2.5")', 'दीवाल कटी (2.5")'),
        ('Fasteners', 'Dewal Kati (3")', 'दीवाल कटी (3")'),
        ('Fasteners', 'Dewal Kati (4")', 'दीवाल कटी (4")'),
        ('Fasteners', 'Screw (19x6)', 'पेच (19x6)'),
        ('Fasteners', 'Screw (25x8)', 'पेच (25x8)'),
        ('Fasteners', 'Screw (35x8)', 'पेच (35x8)'),
        ('Fasteners', 'Screw (50x8)', 'पेच (50x8)'),
        ('Fasteners', 'Screw (75x10)', 'पेच (75x10)'),
        ('Fasteners', 'Gypsum Screw (19x6)', 'जिप्सम पेच (19x6)'),
        ('Fasteners', 'Gypsum Screw (25x8)', 'जिप्सम पेच (25x8)'),
        ('Fasteners', 'Gypsum Screw (35x8)', 'जिप्सम पेच (35x8)'),
        ('Fasteners', 'Gypsum Screw (50x8)', 'जिप्सम पेच (50x8)'),
        ('Fasteners', 'Gypsum Screw (75x10)', 'जिप्सम पेच (75x10)'),
        ('Fasteners', 'Gitti', 'गिट्टी'),
        ('Fasteners', 'Gullu / Stud', 'गुल्लू / स्टड'),
        ('Fasteners', 'Dash Fastener', 'डैश फास्टनर'),
        ('Fasteners', 'Rivet kati', 'रिवेट कटी'),
        ('Fasteners', 'Self-Star Screw (19x6)', 'Self-स्टार पेच (19x6)'),
        ('Fasteners', 'Self-Star Screw (25x8)', 'Self-स्टार पेच (25x8)'),
        ('Fasteners', 'Self-Star Screw (35x8)', 'Self-स्टार पेच (35x8)'),
        ('Fasteners', 'Self-Star Screw (50x8)', 'Self-स्टार पेच (50x8)'),
        ('Fasteners', 'Self-Star Screw (75x10)', 'Self-स्टार पेच (75x10)'),
        ('Fasteners', 'Gullu / Stud (M6)', 'गुल्लू / स्टड (M6)'),
        ('Fasteners', 'Gullu / Stud (M8)', 'गुल्लू / स्टड (M8)'),
        ('Fasteners', 'Gullu / Stud (M10)', 'गुल्लू / स्टड (M10)'),
        ('Fasteners', 'Gullu / Stud (M12)', 'गुल्लू / स्टड (M12)'),
        ('Fasteners', 'Gullu / Stud (M16)', 'गुल्लू / स्टड (M16)'),
        ('Fasteners', 'Gullu / Stud (M20)', 'गुल्लू / स्टड (M20)'),
        ('Fasteners', 'Machine Screw (19x6 mm)', 'मशीन स्क्रू (19x6 मिमी)'),
        ('Fasteners', 'Machine Screw (25x8 mm)', 'मशीन स्क्रू (25x8 मिमी)'),
        ('Fasteners', 'Machine Screw (35x8 mm)', 'मशीन स्क्रू (35x8 मिमी)'),
        ('Fasteners', 'Machine Screw (50x8 mm)', 'मशीन स्क्रू (50x8 मिमी)'),
        ('Fasteners', 'Machine Screw (75x10 mm)', 'मशीन स्क्रू (75x10 मिमी)'),
        ('Fasteners', 'Bolt (2 Suta / M6)', 'बोल्ट (2 सूता / M6)'),
        ('Fasteners', 'Bolt (2.5 Suta / M8)', 'बोल्ट (2.5 सूता / M8)'),
        ('Fasteners', 'Bolt (3 Suta / M10)', 'बोल्ट (3 सूता / M10)'),
        ('Fasteners', 'Bolt (4 Suta / M12)', 'बोल्ट (4 सूता / M12)'),
        ('Fasteners', 'Bolt (5 Suta / M16)', 'बोल्ट (5 सूता / M16)'),
        ('Fasteners', 'Bolt (6 Suta / M20)', 'बोल्ट (6 सूता / M20)'),
        ('Fasteners', 'GI Bolt (2 Suta / M6)', 'GI बोल्ट (2 सूता / M6)'),
        ('Fasteners', 'GI Bolt (2.5 Suta / M8)', 'GI बोल्ट (2.5 सूता / M8)'),
        ('Fasteners', 'GI Bolt (3 Suta / M10)', 'GI बोल्ट (3 सूता / M10)'),
        ('Fasteners', 'GI Bolt (4 Suta / M12)', 'GI बोल्ट (4 सूता / M12)'),
        ('Fasteners', 'GI Bolt (5 Suta / M16)', 'GI बोल्ट (5 सूता / M16)'),
        ('Fasteners', 'GI Bolt (6 Suta / M20)', 'GI बोल्ट (6 सूता / M20)'),
        ('Fasteners', 'Chadar Bolt', 'चादर बोल्ट'),
        ('Fasteners', 'U-Bolt', 'U-बोल्ट'),
        ('Fasteners', 'J-Bolt (6")', 'J-बोल्ट (6")'),
        ('Fasteners', 'J-Bolt (8")', 'J-बोल्ट (8")'),
        ('Fasteners', 'J-Bolt (9")', 'J-बोल्ट (9")'),
        ('Fasteners', 'J-Bolt (10")', 'J-बोल्ट (10")'),
        ('Fasteners', 'J-Bolt (12")', 'J-बोल्ट (12")'),
        ('Fasteners', 'Nut (2 Suta / M6)', 'नट (2 सूता / M6)'),
        ('Fasteners', 'Nut (2.5 Suta / M8)', 'नट (2.5 सूता / M8)'),
        ('Fasteners', 'Nut (3 Suta / M10)', 'नट (3 सूता / M10)'),
        ('Fasteners', 'Nut (4 Suta / M12)', 'नट (4 सूता / M12)'),
        ('Fasteners', 'Nut (5 Suta / M16)', 'नट (5 सूता / M16)'),
        ('Fasteners', 'Nut (6 Suta / M20)', 'नट (6 सूता / M20)'),
        ('Fasteners', 'GI Nut (2 Suta / M6)', 'GI नट (2 सूता / M6)'),
        ('Fasteners', 'GI Nut (2.5 Suta / M8)', 'GI नट (2.5 सूता / M8)'),
        ('Fasteners', 'GI Nut (3 Suta / M10)', 'GI नट (3 सूता / M10)'),
        ('Fasteners', 'GI Nut (4 Suta / M12)', 'GI नट (4 सूता / M12)'),
        ('Fasteners', 'GI Nut (5 Suta / M16)', 'GI नट (5 सूता / M16)'),
        ('Fasteners', 'GI Nut (6 Suta / M20)', 'GI नट (6 सूता / M20)'),
        ('Fasteners', 'Waser (2 Suta / M6)', 'वाशर (2 सूता / M6)'),
        ('Fasteners', 'Waser (2.5 Suta / M8)', 'वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'Waser (3 Suta / M10)', 'वाशर (3 सूता / M10)'),
        ('Fasteners', 'Waser (4 Suta / M12)', 'वाशर (4 सूता / M12)'),
        ('Fasteners', 'Waser (5 Suta / M16)', 'वाशर (5 सूता / M16)'),
        ('Fasteners', 'Waser (6 Suta / M20)', 'वाशर (6 सूता / M20)'),
        ('Fasteners', 'GI Waser (2 Suta / M6)', 'GI वाशर (2 सूता / M6)'),
        ('Fasteners', 'GI Waser (2.5 Suta / M8)', 'GI वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'GI Waser (3 Suta / M10)', 'GI वाशर (3 सूता / M10)'),
        ('Fasteners', 'GI Waser (4 Suta / M12)', 'GI वाशर (4 सूता / M12)'),
        ('Fasteners', 'GI Waser (5 Suta / M16)', 'GI वाशर (5 सूता / M16)'),
        ('Fasteners', 'GI Waser (6 Suta / M20)', 'GI वाशर (6 सूता / M20)'),
        ('Fasteners', 'Spring Waser (2 Suta / M6)', 'स्प्रिंग वाशर (2 सूता / M6)'),
        ('Fasteners', 'Spring Waser (2.5 Suta / M8)', 'स्प्रिंग वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'Spring Waser (3 Suta / M10)', 'स्प्रिंग वाशर (3 सूता / M10)'),
        ('Fasteners', 'Spring Waser (4 Suta / M12)', 'स्प्रिंग वाशर (4 सूता / M12)'),
        ('Fasteners', 'Spring Waser (5 Suta / M16)', 'स्प्रिंग वाशर (5 सूता / M16)'),
        ('Fasteners', 'Spring Waser (6 Suta / M20)', 'स्प्रिंग वाशर (6 सूता / M20)'),
        ('Fasteners', 'GI Spring Waser (2 Suta / M6)', 'GI स्प्रिंग वाशर (2 सूता / M6)'),
        ('Fasteners', 'GI Spring Waser (2.5 Suta / M8)', 'GI स्प्रिंग वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'GI Spring Waser (3 Suta / M10)', 'GI स्प्रिंग वाशर (3 सूता / M10)'),
        ('Fasteners', 'GI Spring Waser (4 Suta / M12)', 'GI स्प्रिंग वाशर (4 सूता / M12)'),
        ('Fasteners', 'GI Spring Waser (5 Suta / M16)', 'GI स्प्रिंग वाशर (5 सूता / M16)'),
        ('Fasteners', 'GI Spring Waser (6 Suta / M20)', 'GI स्प्रिंग वाशर (6 सूता / M20)'),
        ('Building Materials', 'Chhar / Sariya (8mm)', 'छड़ / सरिया (8मिमी)'),
        ('Building Materials', 'Chhar / Sariya (10mm)', 'छड़ / सरिया (10मिमी)'),
        ('Building Materials', 'Chhar / Sariya (12mm)', 'छड़ / सरिया (12मिमी)'),
        ('Building Materials', 'Chhar / Sariya (16mm)', 'छड़ / सरिया (16मिमी)'),
        ('Building Materials', 'Chhar / Sariya (20mm)', 'छड़ / सरिया (20मिमी)'),
        ('Building Materials', 'Chhar / Sariya (25mm)', 'छड़ / सरिया (25मिमी)'),
        ('Building Materials', 'Cement Bori', 'सीमेंट बोरी'),
        ('Building Materials', 'White Cement', 'सफेद सीमेंट'),
        ('Building Materials', 'Loha Chadar', 'लोहा चादर'),
        ('Building Materials', 'Cement Chadar', 'सीमेंट चादर'),
        ('Building Materials', 'Plastic Chadar', 'प्लास्टिक चादर'),
        ('Building Materials', 'Kantedar Tar', 'कांटेदार तार'),

        ('Building Materials', 'Waterproofing Chemical', 'वाटरप्रूफिंग केमिकल'),
        ('Building Materials', 'Shuttering Clamp', 'शटरिंग क्लैंप'),
        ('Building Materials', 'Bans (8 ft)', 'बांस (8 फीट)'),
        ('Building Materials', 'Bans (12 ft)', 'बांस (12 फीट)'),
        ('Building Materials', 'Naariyal Rassi (6mm)', 'नारियल रस्सी (6मिमी)'),
        ('Building Materials', 'Naariyal Rassi (10mm)', 'नारियल रस्सी (10मिमी)'),
        ('Building Materials', 'Nylon Rassi (6mm)', 'नायलॉन रस्सी (6मिमी)'),
        ('Building Materials', 'Nylon Rassi (10mm)', 'नायलॉन रस्सी (10मिमी)'),
        ('Building Materials', 'Jute Rassi (8mm)', 'Jute रस्सी (8मिमी)'),
        ('Building Materials', 'Bora', 'Bora'),
        ('Building Materials', 'GI Taar (14 SWG / 2.03 mm)', 'GI तार (14 SWG / 2.03 मिमी)'),
        ('Building Materials', 'GI Taar (16 SWG / 2.03 mm)', 'GI तार (16 SWG / 2.03 मिमी)'),
        ('Building Materials', 'GI Taar (18 SWG / 2.03 mm)', 'GI तार (18 SWG / 2.03 मिमी)'),
        ('Building Materials', 'GI Taar (20 SWG / 2.03 mm)', 'GI तार (20 SWG / 2.03 मिमी)'),
        ('Building Materials', 'Taar (16 SWG / 1.63 mm)', 'तार (16 SWG / 1.63 मिमी)'),
        ('Building Materials', 'Taar (18 SWG / 1.22 mm)', 'तार (18 SWG / 1.22 मिमी)'),
        ('Building Materials', 'Taar (20 SWG / 0.91 mm)', 'तार (20 SWG / 0.91 मिमी)'),
        ('Building Materials', 'Taar (22 SWG / 0.71 mm)', 'तार (22 SWG / 0.71 मिमी)'),
        ('Building Materials', 'Putty (1 Kg)', 'पुट्टी (1 किलो)'),
        ('Building Materials', 'Putty (2 Kg)', 'पुट्टी (2 किलो)'),
        ('Building Materials', 'Putty (5 Kg)', 'पुट्टी (5 किलो)'),
        ('Building Materials', 'Putty (10 Kg)', 'पुट्टी (10 किलो)'),
        ('Building Materials', 'Putty (25 Kg)', 'पुट्टी (25 किलो)'),
        ('Building Materials', 'Putty (50 Kg)', 'पुट्टी (50 किलो)'),
        ('Hand Tools', 'Hathauri (100 g)', 'हथौड़ी (100 ग्राम)'),
        ('Hand Tools', 'Hathauri (200 g)', 'हथौड़ी (200 ग्राम)'),
        ('Hand Tools', 'Hathauri (250 g)', 'हथौड़ी (250 ग्राम)'),
        ('Hand Tools', 'Hathauri (300 g)', 'हथौड़ी (300 ग्राम)'),
        ('Hand Tools', 'Hathauri (500 g)', 'हथौड़ी (500 ग्राम)'),
        ('Hand Tools', 'Hathauri (750 g)', 'हथौड़ी (750 ग्राम)'),
        ('Hand Tools', 'Hathauri (1 Kg)', 'हथौड़ी (1 किलो)'),
        ('Hand Tools', 'Hathauri (1.5 Kg)', 'हथौड़ी (1.5 किलो)'),
        ('Hand Tools', 'Hathaura (2 Kg)', 'हथौड़ा (2 किलो)'),
        ('Hand Tools', 'Hathaura (3 Kg)', 'हथौड़ा (3 किलो)'),
        ('Hand Tools', 'Hathaura (4 Kg)', 'हथौड़ा (4 किलो)'),
        ('Hand Tools', 'Hathaura (5 Kg)', 'हथौड़ा (5 किलो)'),
        ('Hand Tools', 'Hathaura (6 Kg)', 'हथौड़ा (6 किलो)'),
        ('Hand Tools', 'Hathaura (8 Kg)', 'हथौड़ा (8 किलो)'),
        ('Hand Tools', 'Hathaura (10 Kg)', 'हथौड़ा 10 किलो)'),
        ('Hand Tools', 'Plass', 'प्लास'),
        ('Hand Tools', 'Noki Plass', 'नोकी प्लास'),
        ('Hand Tools', 'Silai Paana', 'सिलाई पाना'),

        ('Hand Tools', 'Pipe Wrench', 'पाइप रिंच'),
        ('Hand Tools', 'Pechkas (Chapa)', 'पेचकस (Chapa)'),
        ('Hand Tools', 'Pechkas (Star)', 'पेचकस (Star)'),
        ('Hand Tools', 'Tester', 'टेस्टर'),
        ('Hand Tools', 'Chheni (6")', 'छेनी (6")'),
        ('Hand Tools', 'Chheni (8")', 'छेनी (8")'),
        ('Hand Tools', 'Chheni (10")', 'छेनी (10")'),
        ('Hand Tools', 'Chheni (12")', 'छेनी (12")'),
        ('Hand Tools', 'Loha Aari Frame', 'लोहा आरी फ्रेम'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10", 18 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10", 18 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10", 24 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10", 24 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10", 32 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10", 32 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12", 18 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12", 18 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12", 24 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12", 24 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12", 32 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12", 32 TPI)'),
        ('Hand Tools', 'Randa', 'रंदा'),
        ('Hand Tools', 'Randa Patti', 'रंदा पट्टी'),
        ('Hand Tools', 'Bada Feeta', 'बड़ा फीता'),
        ('Hand Tools', 'Level Rular / Water Level', 'लेवल Rular / पानी लेवल'),
        ('Hand Tools', 'Guniya', 'गुनिया'),
        ('Hand Tools', 'Tar Cutter', 'तार कटर'),
        ('Hand Tools', 'Chadar Katne Wali Ka"i', 'चादर काटने वाली Ka"i'),
        ('Hand Tools', 'Allen Key Set', 'Allen की सेट'),
        ('Hand Tools', 'Reti (Flat, 6")', 'रेती (चपटी, 6")'),
        ('Hand Tools', 'Reti (Flat, 8")', 'रेती (चपटी, 8")'),
        ('Hand Tools', 'Reti (Flat, 10")', 'रेती (चपटी, 10")'),
        ('Hand Tools', 'Reti (Flat, 12")', 'रेती (चपटी, 12")'),
        ('Hand Tools', 'Reti (Flat, 14")', 'रेती (चपटी, 14")'),
        ('Hand Tools', 'Reti (Round, 6")', 'रेती (गोल, 6")'),
        ('Hand Tools', 'Reti (Round, 8")', 'रेती (गोल, 8")'),
        ('Hand Tools', 'Reti (Round, 10")', 'रेती (गोल, 10")'),
        ('Hand Tools', 'Reti (Round, 12")', 'रेती (गोल, 12")'),
        ('Hand Tools', 'Reti (Round, 14")', 'रेती (गोल, 14")'),
        ('Hand Tools', 'Reti (Half-Round, 6")', 'रेती (अर्ध-गोल, 6")'),
        ('Hand Tools', 'Reti (Half-Round, 8")', 'रेती (अर्ध-गोल, 8")'),
        ('Hand Tools', 'Reti (Half-Round, 10")', 'रेती (अर्ध-गोल, 10")'),
        ('Hand Tools', 'Reti (Half-Round, 12")', 'रेती (अर्ध-गोल, 12")'),
        ('Hand Tools', 'Reti (Half-Round, 14")', 'रेती (अर्ध-गोल, 14")'),
        ('Hand Tools', 'Reti (Square, 6")', 'रेती (चौकोर, 6")'),
        ('Hand Tools', 'Reti (Square, 8")', 'रेती (चौकोर, 8")'),
        ('Hand Tools', 'Reti (Square, 10")', 'रेती (चौकोर, 10")'),
        ('Hand Tools', 'Reti (Square, 12")', 'रेती (चौकोर, 12")'),
        ('Hand Tools', 'Reti (Triangular, 6")', 'रेती (तिकोनी, 6")'),
        ('Hand Tools', 'Reti (Triangular, 8")', 'रेती (तिकोनी, 8")'),
        ('Hand Tools', 'Reti (Triangular, 10")', 'रेती (तिकोनी, 10")'),
        ('Hand Tools', 'Reti (Triangular, 12")', 'रेती (तिकोनी, 12")'),
        ('Hand Tools', 'Sariya Cutter / Bolt Cutter', 'सरिया कटर / बोल्ट कटर'),
        ('Hand Tools', 'Punch', 'पंच'),
        ('Hand Tools', 'Sabal / Khananti', 'सब्बल / खनन्ती'),
        ('Hand Tools', 'Badhai Cheer Aari (18")', 'बढ़ई Cheer आरी (18")'),
        ('Hand Tools', 'Tenon Aari (10")', 'Tenon आरी (10")'),
        ('Hand Tools', 'Basula/Chheni Set (6mm-25mm)', 'बसूला/छेनी सेट (6मिमी-25मिमी)'),
        ('Hand Tools', 'Basula/Chheni (6 mm / 0.25")', 'बसूला/छेनी (6 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (10 mm / 0.375")', 'बसूला/छेनी (10 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (12 mm / 0.5")', 'बसूला/छेनी (12 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (19 mm / 0.75")', 'बसूला/छेनी (19 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (25 mm / 1")', 'बसूला/छेनी (25 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (32 mm / 1.25")', 'बसूला/छेनी (32 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (38 mm / 1.5")', 'बसूला/छेनी (38 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (6 mm)', 'मोर्टिस छेनी (6 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (10 mm)', 'मोर्टिस छेनी (10 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (12 mm)', 'मोर्टिस छेनी (12 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (16 mm)', 'मोर्टिस छेनी (16 मिमी)'),
        ('Hand Tools', 'Lakdi ka Mogra', 'Lakdi का मोगरा'),
        ('Hand Tools', 'Randa (No. 4)', 'रंदा (नंबर 4)'),
        ('Hand Tools', 'Jack Randa (No. 5)', 'Jack रंदा (नंबर 5)'),
        ('Hand Tools', 'Marking Gauge', 'Marking Gauge'),
        ('Hand Tools', 'Soot Dhaga Reel', 'Soot धागा Reel'),
        ('Hand Tools', 'Badhai Pencil', 'बढ़ई Pencil'),
        ('Hand Tools', 'Bevel', 'Bevel'),
        ('Hand Tools', 'Barma (6mm-25mm bit)', 'Barma (6मिमी-25मिमी bit)'),
        ('Hand Tools', 'Sooja', 'सूजा'),
        ('Hand Tools', 'C-Clamp (2")', 'C-क्लैंप (2")'),
        ('Hand Tools', 'C-Clamp (4")', 'C-क्लैंप (4")'),
        ('Hand Tools', 'C-Clamp (6")', 'C-क्लैंप (6")'),
        ('Hand Tools', 'G-Clamp (4")', 'G-क्लैंप (4")'),
        ('Hand Tools', 'G-Clamp (6")', 'G-क्लैंप (6")'),
        ('Hand Tools', 'Badhai Shikanja (4")', 'बढ़ई शिकंजा (4")'),
        ('Hand Tools', 'Badhai Shikanja (6")', 'बढ़ई शिकंजा (6")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 8")', 'खुरदरी रेती - लकड़ी (चपटी, 8")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 10")', 'खुरदरी रेती - लकड़ी (चपटी, 10")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 12")', 'खुरदरी रेती - लकड़ी (चपटी, 12")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 8")', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 8")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 10")', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 10")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 12")', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 12")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 8")', 'खुरदरी रेती - लकड़ी (गोल, 8")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 10")', 'खुरदरी रेती - लकड़ी (गोल, 10")'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 12")', 'खुरदरी रेती - लकड़ी (गोल, 12")'),
        ('Hand Tools', 'Keel Punch', 'Keel पंच'),
        ('Hand Tools', 'Polish Brush (1")', 'पॉलिश ब्रश (1")'),
        ('Hand Tools', 'Polish Brush (2")', 'पॉलिश ब्रश (2")'),
        ('Hand Tools', 'Karya Mez', 'कार्य मेज़'),
        ('Hand Tools', 'Taar Wala Brush', 'तार वाला ब्रश'),
        ('Hand Tools', 'Toilet Brush', 'टॉयलेट ब्रश'),
        ('Hand Tools', 'Taarkol Brush (3")', 'Taarkol ब्रश (3")'),
        ('Hand Tools', 'Ragadne Wala Brush', 'रगड़ने वाला ब्रश'),
        ('Hand Tools', 'Aari (8")', 'आरी (8")'),
        ('Hand Tools', 'Aari (10")', 'आरी (10")'),
        ('Hand Tools', 'Aari (12")', 'आरी (12")'),
        ('Hand Tools', 'Aari (14")', 'आरी (14")'),
        ('Hand Tools', 'Aari (18")', 'आरी (18")'),
        ('Hand Tools', 'Aari (24")', 'आरी (24")'),
        ('Hand Tools', 'Saahul (100 g)', 'साहुल (100 ग्राम)'),
        ('Hand Tools', 'Saahul (200 g)', 'साहुल (200 ग्राम)'),
        ('Hand Tools', 'Saahul (250 g)', 'साहुल (250 ग्राम)'),
        ('Hand Tools', 'Saahul (500 g)', 'साहुल (500 ग्राम)'),
        ('Hand Tools', 'Karni (4")', 'करनी (4")'),
        ('Hand Tools', 'Karni (5")', 'करनी (5")'),
        ('Hand Tools', 'Karni (6")', 'करनी (6")'),
        ('Hand Tools', 'Karni (7")', 'करनी (7")'),
        ('Power Tools', 'Hole Machine / Drill Machine', 'Hole मशीन / ड्रिल मशीन'),
        ('Power Tools', 'Chitai Machine / Demolition Drill', 'Chitai मशीन / Demolition ड्रिल'),
        ('Power Tools', 'Grinder Machine / Glazer', 'Grinder मशीन / Glazer'),
        ('Power Tools', 'Tile Katne Wali Machine', 'टाइल काटने वाली मशीन'),
        ('Power Tools', 'Bijli Randa Machine', 'बिजली रंदा मशीन'),
        ('Power Tools', 'Gol Aari Machine', 'गोल आरी मशीन'),
        ('Power Tools', 'Jigsaw Machine', 'जिगसॉ मशीन'),
        ('Power Tools', 'Battery Drill Machine', 'Battery ड्रिल मशीन'),
        ('Power Tools', 'Dewal Bit (5mm)', 'दीवाल बिट (5मिमी)'),
        ('Power Tools', 'Dewal Bit (6mm)', 'दीवाल बिट (6मिमी)'),
        ('Power Tools', 'Dewal Bit (8mm)', 'दीवाल बिट (8मिमी)'),
        ('Power Tools', 'Dewal Bit (10mm)', 'दीवाल बिट (10मिमी)'),
        ('Power Tools', 'Dewal Bit (12mm)', 'दीवाल बिट (12मिमी)'),
        ('Power Tools', 'Dewal Bit (14mm)', 'दीवाल बिट (14मिमी)'),
        ('Power Tools', 'Dewal Bit (16mm)', 'दीवाल बिट (16मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (5mm)', 'लोहा/लकड़ी बिट (5मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (6mm)', 'लोहा/लकड़ी बिट (6मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (8mm)', 'लोहा/लकड़ी बिट (8मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (10mm)', 'लोहा/लकड़ी बिट (10मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (12mm)', 'लोहा/लकड़ी बिट (12मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (14mm)', 'लोहा/लकड़ी बिट (14मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (16mm)', 'लोहा/लकड़ी बिट (16मिमी)'),
        ('Power Tools', 'Marbal Patti / Diamond Blade', 'Marbal पट्टी / डायमंड ब्लेड'),
        ('Power Tools', 'Grinding Pathar', 'ग्राइंडिंग Pathar'),
        ('Power Tools', 'Loha Kata Patti', 'लोहा कटा पट्टी'),
        ('Power Tools', 'Polishing Disc', 'Polishing Disc'),
        ('Power Tools', 'Machine Carbon', 'मशीन Carbon'),
        ('Power Tools', 'Drill Chabi & Chuck', 'ड्रिल चाबी & चक'),
        ('Plumbing', 'CPVC (0.5" SDR 11)', 'सीपीवीसी (0.5" SDR 11)'),
        ('Plumbing', 'CPVC (0.75" SDR 11)', 'सीपीवीसी (0.75" SDR 11)'),
        ('Plumbing', 'CPVC (1" SDR 11)', 'सीपीवीसी (1" SDR 11)'),
        ('Plumbing', 'CPVC (1.25" SDR 11)', 'सीपीवीसी (1.25" SDR 11)'),
        ('Plumbing', 'CPVC (1.5" SDR 11)', 'सीपीवीसी (1.5" SDR 11)'),
        ('Plumbing', 'CPVC (2" SDR 11)', 'सीपीवीसी (2" SDR 11)'),
        ('Plumbing', 'UPVC Pipe (0.5", 10 ft)', 'UPVC पाइप (0.5", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (0.75", 10 ft)', 'UPVC पाइप (0.75", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1", 10 ft)', 'UPVC पाइप (1", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1.25", 10 ft)', 'UPVC पाइप (1.25", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1.5", 10 ft)', 'UPVC पाइप (1.5", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (2", 10 ft)', 'UPVC पाइप (2", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (3", 10 ft)', 'UPVC पाइप (3", 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (4", 10 ft)', 'UPVC पाइप (4", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1", 10 ft)', 'खेती/नाला पाइप (1", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1.25", 10 ft)', 'खेती/नाला पाइप (1.25", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1.5", 10 ft)', 'खेती/नाला पाइप (1.5", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (2", 10 ft)', 'खेती/नाला पाइप (2", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (3", 10 ft)', 'खेती/नाला पाइप (3", 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (4", 10 ft)', 'खेती/नाला पाइप (4", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (0.5", 10 ft)', 'लोहा पाइप (0.5", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (0.75", 10 ft)', 'लोहा पाइप (0.75", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1", 10 ft)', 'लोहा पाइप (1", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1.25", 10 ft)', 'लोहा पाइप (1.25", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1.5", 10 ft)', 'लोहा पाइप (1.5", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (2", 10 ft)', 'लोहा पाइप (2", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (3", 10 ft)', 'लोहा पाइप (3", 10 फीट)'),
        ('Plumbing', 'Loha Pipe (4", 10 ft)', 'लोहा पाइप (4", 10 फीट)'),
        ('Plumbing', 'CPVC Elbow (0.5")', 'सीपीवीसी एल्बो (0.5")'),
        ('Plumbing', 'CPVC Elbow (0.75")', 'सीपीवीसी एल्बो (0.75")'),
        ('Plumbing', 'CPVC Elbow (1")', 'सीपीवीसी एल्बो (1")'),
        ('Plumbing', 'CPVC Elbow (1.25")', 'सीपीवीसी एल्बो (1.25")'),
        ('Plumbing', 'CPVC Elbow (1.5")', 'सीपीवीसी एल्बो (1.5")'),
        ('Plumbing', 'CPVC Elbow (2")', 'सीपीवीसी एल्बो (2")'),
        ('Plumbing', 'CPVC Tee / T-Joint (0.5")', 'सीपीवीसी टी / T-Joint (0.5")'),
        ('Plumbing', 'CPVC Tee / T-Joint (0.75")', 'सीपीवीसी टी / T-Joint (0.75")'),
        ('Plumbing', 'CPVC Tee / T-Joint (1")', 'सीपीवीसी टी / T-Joint (1")'),
        ('Plumbing', 'CPVC Tee / T-Joint (1.25")', 'सीपीवीसी टी / T-Joint (1.25")'),
        ('Plumbing', 'CPVC Tee / T-Joint (1.5")', 'सीपीवीसी टी / T-Joint (1.5")'),
        ('Plumbing', 'CPVC Tee / T-Joint (2")', 'सीपीवीसी टी / T-Joint (2")'),
        ('Plumbing', 'CPVC Socket (0.5")', 'सीपीवीसी सॉकेट (0.5")'),
        ('Plumbing', 'CPVC Socket (0.75")', 'सीपीवीसी सॉकेट (0.75")'),
        ('Plumbing', 'CPVC Socket (1")', 'सीपीवीसी सॉकेट (1")'),
        ('Plumbing', 'CPVC Socket (1.25")', 'सीपीवीसी सॉकेट (1.25")'),
        ('Plumbing', 'CPVC Socket (1.5")', 'सीपीवीसी सॉकेट (1.5")'),
        ('Plumbing', 'CPVC Socket (2")', 'सीपीवीसी सॉकेट (2")'),
        ('Plumbing', 'CPVC Union', 'सीपीवीसी Union'),
        ('Plumbing', 'Reducer / Ghatane Wala', 'Reducer / Ghatane वाला'),
        ('Plumbing', 'Ball Valve / Chabi / Handle', 'बॉल वाल्व / चाबी / हैंडल'),
        ('Plumbing', 'Brass MTA', 'पीतल MTA'),
        ('Plumbing', 'Brass FTA', 'पीतल FTA'),
        ('Plumbing', 'Brass Elbow (Nal Point)', 'पीतल एल्बो (Nal Point)'),
        ('Plumbing', 'CPVC Solution / Gum', 'सीपीवीसी सोल्यूशन / गोंद'),
        ('Plumbing', 'UPVC Solution', 'यूपीवीसी सोल्यूशन'),
        ('Plumbing', 'Slipping Grease / Lubricant', 'Slipping ग्रीस / Lubricant'),
        ('Plumbing', 'Teflon Tape (12 mm)', 'टेफ्लॉन टेप (12 मिमी x 5 मी)'),
        ('Plumbing', 'Teflon Tape (12 mm)', 'टेफ्लॉन टेप (12 मिमी x 10 मी)'),
        ('Plumbing', 'Teflon Tape (19 mm)', 'टेफ्लॉन टेप (19 मिमी x 10 मी)'),
        ('Plumbing', 'Teflon Tape (25 mm)', 'टेफ्लॉन टेप (25 मिमी x 10 मी)'),
        ('Plumbing', 'Sutli / Dhaga', 'सुतली / धागा'),
        ('Plumbing', 'M-Seal (30 g)', 'एम-सील (30 ग्राम)'),
        ('Plumbing', 'M-Seal (50 g)', 'एम-सील (50 ग्राम)'),
        ('Plumbing', 'M-Seal (100 g)', 'एम-सील (100 ग्राम)'),
        ('Plumbing', 'M-Seal (200 g)', 'एम-सील (200 ग्राम)'),
        ('Plumbing', 'M-Seal (500 g)', 'एम-सील (500 ग्राम)'),
        ('Plumbing', 'M-Seal (1 Kg)', 'एम-सील (1 किलो)'),
        ('Plumbing', 'Nal / Totii', 'नल / टॉटी'),
        ('Plumbing', 'Basin Nal', 'बेसिन नल'),
        ('Plumbing', 'Angle Valve', 'एंगल वाल्व'),
        ('Plumbing', 'Concealed Wall Valve', 'छुपा हुआ दीवाल वाल्व'),
        ('Plumbing', 'Spray', 'स्प्रे '),
        ('Plumbing', 'Jharana / Shower', 'झरना / शावर'),
        ('Plumbing', 'Connection Pipe', 'कनेक्शन पाइप'),
        ('Plumbing', 'Sink Pipe', 'सिंक पाइप'),
        ('Plumbing', 'Jali Trap / Bottle Trap', 'जाली ट्रैप / Bottle ट्रैप'),
        ('Plumbing', 'Floor Jali (4x4")', 'ज़मीन जाली (4x4")'),
        ('Plumbing', 'Floor Jali (5x5")', 'ज़मीन जाली (5x5")'),
        ('Plumbing', 'Floor Jali (6x6")', 'ज़मीन जाली (6x6")'),
        ('Plumbing', 'Steel Floor Jali (4x4")', 'स्टील ज़मीन जाली (4x4")'),
        ('Plumbing', 'Steel Floor Jali (5x5")', 'स्टील ज़मीन जाली (5x5")'),
        ('Plumbing', 'Steel Floor Jali (6x6")', 'स्टील ज़मीन जाली (6x6")'),
        ('Plumbing', 'Nahani Trap', 'नहानी ट्रैप'),

        ('Plumbing', 'Auto-Cut Valve / Ball Cock', 'Auto-Cut वाल्व / बॉल Cock'),
        ('Plumbing', 'Delivery Pipe / Delivery Hose', 'डिलीवरी पाइप / डिलीवरी Hose'),
        ('Plumbing', 'Water Pipe / Level Pipe', 'पानी पाइप / लेवल पाइप'),
        ('Plumbing', 'Pipe Clamp / Patti', 'पाइप क्लैंप / पट्टी'),
        ('Plumbing', 'PVC Saddle / Clamp', 'पीवीसी Saddle / क्लैंप'),
        ('Plumbing', 'UPVC Elbow (0.5")', 'यूपीवीसी एल्बो (0.5")'),
        ('Plumbing', 'UPVC Elbow (0.75")', 'यूपीवीसी एल्बो (0.75")'),
        ('Plumbing', 'UPVC Elbow (1")', 'यूपीवीसी एल्बो (1")'),
        ('Plumbing', 'UPVC Elbow (1.5")', 'यूपीवीसी एल्बो (1.5")'),
        ('Plumbing', 'UPVC Elbow (2")', 'यूपीवीसी एल्बो (2")'),
        ('Plumbing', 'UPVC Elbow (3")', 'यूपीवीसी एल्बो (3")'),
        ('Plumbing', 'UPVC Elbow (4")', 'यूपीवीसी एल्बो (4")'),
        ('Plumbing', 'UPVC Tee (0.5")', 'यूपीवीसी टी (0.5")'),
        ('Plumbing', 'UPVC Tee (0.75")', 'यूपीवीसी टी (0.75")'),
        ('Plumbing', 'UPVC Tee (1")', 'यूपीवीसी टी (1")'),
        ('Plumbing', 'UPVC Tee (1.5")', 'यूपीवीसी टी (1.5")'),
        ('Plumbing', 'UPVC Tee (2")', 'यूपीवीसी टी (2")'),
        ('Plumbing', 'UPVC Tee (3")', 'यूपीवीसी टी (3")'),
        ('Plumbing', 'UPVC Tee (4")', 'यूपीवीसी टी (4")'),
        ('Plumbing', 'UPVC Socket (0.5")', 'यूपीवीसी सॉकेट (0.5")'),
        ('Plumbing', 'UPVC Socket (0.75")', 'यूपीवीसी सॉकेट (0.75")'),
        ('Plumbing', 'UPVC Socket (1")', 'यूपीवीसी सॉकेट (1")'),
        ('Plumbing', 'UPVC Socket (1.5")', 'यूपीवीसी सॉकेट (1.5")'),
        ('Plumbing', 'UPVC Socket (2")', 'यूपीवीसी सॉकेट (2")'),
        ('Plumbing', 'UPVC Socket (3")', 'यूपीवीसी सॉकेट (3")'),
        ('Plumbing', 'UPVC Socket (4")', 'यूपीवीसी सॉकेट (4")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (0.5")', 'पीवीसी नाला/एग्री एल्बो (0.5")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (0.75")', 'पीवीसी नाला/एग्री एल्बो (0.75")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (1")', 'पीवीसी नाला/एग्री एल्बो (1")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (1.5")', 'पीवीसी नाला/एग्री एल्बो (1.5")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (2")', 'पीवीसी नाला/एग्री एल्बो (2")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (3")', 'पीवीसी नाला/एग्री एल्बो (3")'),
        ('Plumbing', 'PVC Nala/Agri Elbow (4")', 'पीवीसी नाला/एग्री एल्बो (4")'),
        ('Plumbing', 'PVC Agri Tee (0.5")', 'पीवीसी एग्री टी (0.5")'),
        ('Plumbing', 'PVC Agri Tee (0.75")', 'पीवीसी एग्री टी (0.75")'),
        ('Plumbing', 'PVC Agri Tee (1")', 'पीवीसी एग्री टी (1")'),
        ('Plumbing', 'PVC Agri Tee (1.5")', 'पीवीसी एग्री टी (1.5")'),
        ('Plumbing', 'PVC Agri Tee (2")', 'पीवीसी एग्री टी (2")'),
        ('Plumbing', 'PVC Agri Tee (3")', 'पीवीसी एग्री टी (3")'),
        ('Plumbing', 'PVC Agri Tee (4")', 'पीवीसी एग्री टी (4")'),
        ('Plumbing', 'SWR Coupler (0.5")', 'एसडब्ल्यूआर कपलर (0.5")'),
        ('Plumbing', 'SWR Coupler (0.75")', 'एसडब्ल्यूआर कपलर (0.75")'),
        ('Plumbing', 'SWR Coupler (1")', 'एसडब्ल्यूआर कपलर (1")'),
        ('Plumbing', 'SWR Coupler (1.5")', 'एसडब्ल्यूआर कपलर (1.5")'),
        ('Plumbing', 'SWR Coupler (2")', 'एसडब्ल्यूआर कपलर (2")'),
        ('Plumbing', 'SWR Coupler (3")', 'एसडब्ल्यूआर कपलर (3")'),
        ('Plumbing', 'SWR Coupler (4")', 'एसडब्ल्यूआर कपलर (4")'),
        ('Plumbing', 'SWR Door Kona (0.5")', 'एसडब्ल्यूआर दरवाज़ा कोना (0.5")'),
        ('Plumbing', 'SWR Door Kona (0.75")', 'एसडब्ल्यूआर दरवाज़ा कोना (0.75")'),
        ('Plumbing', 'SWR Door Kona (1")', 'एसडब्ल्यूआर दरवाज़ा कोना (1")'),
        ('Plumbing', 'SWR Door Kona (1.5")', 'एसडब्ल्यूआर दरवाज़ा कोना (1.5")'),
        ('Plumbing', 'SWR Door Kona (2")', 'एसडब्ल्यूआर दरवाज़ा कोना (2")'),
        ('Plumbing', 'SWR Door Kona (3")', 'एसडब्ल्यूआर दरवाज़ा कोना (3")'),
        ('Plumbing', 'SWR Door Kona (4")', 'एसडब्ल्यूआर दरवाज़ा कोना (4")'),
        ('Plumbing', 'SWR Y-Joint (0.5")', 'एसडब्ल्यूआर Y-Joint (0.5")'),
        ('Plumbing', 'SWR Y-Joint (0.75")', 'एसडब्ल्यूआर Y-Joint (0.75")'),
        ('Plumbing', 'SWR Y-Joint (1")', 'एसडब्ल्यूआर Y-Joint (1")'),
        ('Plumbing', 'SWR Y-Joint (1.5")', 'एसडब्ल्यूआर Y-Joint (1.5")'),
        ('Plumbing', 'SWR Y-Joint (2")', 'एसडब्ल्यूआर Y-Joint (2")'),
        ('Plumbing', 'SWR Y-Joint (3")', 'एसडब्ल्यूआर Y-Joint (3")'),
        ('Plumbing', 'SWR Y-Joint (4")', 'एसडब्ल्यूआर Y-Joint (4")'),
        ('Plumbing', 'Loha Elbow (0.5")', 'लोहा एल्बो (0.5")'),
        ('Plumbing', 'Loha Elbow (0.75")', 'लोहा एल्बो (0.75")'),
        ('Plumbing', 'Loha Elbow (1")', 'लोहा एल्बो (1")'),
        ('Plumbing', 'Loha Elbow (1.5")', 'लोहा एल्बो (1.5")'),
        ('Plumbing', 'Loha Elbow (2")', 'लोहा एल्बो (2")'),
        ('Plumbing', 'Loha Elbow (3")', 'लोहा एल्बो (3")'),
        ('Plumbing', 'Loha Elbow (4")', 'लोहा एल्बो (4")'),
        ('Plumbing', 'Loha Tee (0.5")', 'लोहा टी (0.5")'),
        ('Plumbing', 'Loha Tee (0.75")', 'लोहा टी (0.75")'),
        ('Plumbing', 'Loha Tee (1")', 'लोहा टी (1")'),
        ('Plumbing', 'Loha Tee (1.5")', 'लोहा टी (1.5")'),
        ('Plumbing', 'Loha Tee (2")', 'लोहा टी (2")'),
        ('Plumbing', 'Loha Tee (3")', 'लोहा टी (3")'),
        ('Plumbing', 'Loha Tee (4")', 'लोहा टी (4")'),
        ('Plumbing', 'Loha Socket (0.5")', 'लोहा सॉकेट (0.5")'),
        ('Plumbing', 'Loha Socket (0.75")', 'लोहा सॉकेट (0.75")'),
        ('Plumbing', 'Loha Socket (1")', 'लोहा सॉकेट (1")'),
        ('Plumbing', 'Loha Socket (1.5")', 'लोहा सॉकेट (1.5")'),
        ('Plumbing', 'Loha Socket (2")', 'लोहा सॉकेट (2")'),
        ('Plumbing', 'Loha Socket (3")', 'लोहा सॉकेट (3")'),
        ('Plumbing', 'Loha Socket (4")', 'लोहा सॉकेट (4")'),
        ('Plumbing', 'Nipple (0.5" x 2")', 'निप्पल (0.5" x 2")'),
        ('Plumbing', 'Nipple (0.5" x 4")', 'निप्पल (0.5" x 4")'),
        ('Plumbing', 'Nipple (0.5" x 6")', 'निप्पल (0.5" x 6")'),
        ('Plumbing', 'Nipple (0.5" x 8")', 'निप्पल (0.5" x 8")'),
        ('Plumbing', 'Nipple (0.5" x 9")', 'निप्पल (0.5" x 9")'),
        ('Plumbing', 'Nipple (0.5" x 12")', 'निप्पल (0.5" x 12")'),
        ('Plumbing', 'Nipple (0.5" x 10 ft)', 'निप्पल (0.5" x 10 फीट)'),
        ('Plumbing', 'Nepul (0.75" x 2")', 'नेपुल (0.75" x 2")'),
        ('Plumbing', 'Nepul (0.75" x 4")', 'नेपुल (0.75" x 4")'),
        ('Plumbing', 'Nepul (0.75" x 6")', 'नेपुल (0.75" x 6")'),
        ('Plumbing', 'Nepul (0.75" x 8")', 'नेपुल (0.75" x 8")'),
        ('Plumbing', 'Nepul (0.75" x 9")', 'नेपुल (0.75" x 9")'),
        ('Plumbing', 'Nepul (0.75" x 12")', 'नेपुल (0.75" x 12")'),
        ('Plumbing', 'Nepul (0.75" x 10 ft)', 'नेपुल (0.75" x 10 फीट)'),
        ('Plumbing', 'Nepul (1" x 2")', 'नेपुल (1" x 2")'),
        ('Plumbing', 'Nepul (1" x 4")', 'नेपुल (1" x 4")'),
        ('Plumbing', 'Nepul (1" x 6")', 'नेपुल (1" x 6")'),
        ('Plumbing', 'Nepul (1" x 8")', 'नेपुल (1" x 8")'),
        ('Plumbing', 'Nepul (1" x 9")', 'नेपुल (1" x 9")'),
        ('Plumbing', 'Nepul (1" x 12")', 'नेपुल (1" x 12")'),
        ('Plumbing', 'Nepul (1" x 10 ft)', 'नेपुल (1" x 10 फीट)'),
        ('Plumbing', 'Nepul (1.5" x 2")', 'नेपुल (1.5" x 2")'),
        ('Plumbing', 'Nepul (1.5" x 4")', 'नेपुल (1.5" x 4")'),
        ('Plumbing', 'Nepul (1.5" x 6")', 'नेपुल (1.5" x 6")'),
        ('Plumbing', 'Nepul (1.5" x 8")', 'नेपुल (1.5" x 8")'),
        ('Plumbing', 'Nepul (1.5" x 9")', 'नेपुल (1.5" x 9")'),
        ('Plumbing', 'Nepul (1.5" x 12")', 'नेपुल (1.5" x 12")'),
        ('Plumbing', 'Nepul (1.5" x 10 ft)', 'नेपुल (1.5" x 10 फीट)'),
        
        ('Plumbing', 'Brass Stop Valve (0.5")', 'पीतल स्टॉप वाल्व (0.5")'),
        ('Plumbing', 'Brass Stop Valve (0.75")', 'पीतल स्टॉप वाल्व (0.75")'),
        ('Plumbing', 'Brass Stop Valve (1")', 'पीतल स्टॉप वाल्व (1")'),
        ('Plumbing', 'Brass Stop Valve (1.5")', 'पीतल स्टॉप वाल्व (1.5")'),
        ('Plumbing', 'Brass Stop Valve (2")', 'पीतल स्टॉप वाल्व (2")'),
        ('Plumbing', 'Brass Stop Valve (3")', 'पीतल स्टॉप वाल्व (3")'),
        ('Plumbing', 'Brass Stop Valve (4")', 'पीतल स्टॉप वाल्व (4")'),
        ('Door Hardware', 'Lock (Heavy)', 'ताला (Heavy)'),
        ('Door Hardware', 'Shutter Lock', 'शटर ताला'),
        ('Door Hardware', 'Handle Lock Set', 'हैंडल लॉक / ताला सेट'),
        ('Door Hardware', 'Gol Lock / Bedroom Lock', 'गोल लॉक / ताला / Bedroom लॉक / ताला'),
        ('Door Hardware', 'Draj Lock / Box Lock', 'Draj लॉक / ताला / बॉक्स लॉक / ताला'),
        ('Door Hardware', 'Gate Lock / Rim Lock', 'Gate लॉक / ताला / Rim लॉक / ताला'),
        ('Door Hardware', 'Kabja (2")', 'कब्जा (2")'),
        ('Door Hardware', 'Kabja (3")', 'कब्जा (3")'),
        ('Door Hardware', 'Kabja (4")', 'कब्जा (4")'),
        ('Door Hardware', 'Kabja (5")', 'कब्जा (5")'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (2")', 'बॉक्स कब्जा / L-Bihari कब्जा (2")'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (3")', 'बॉक्स कब्जा / L-Bihari कब्जा (3")'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (4")', 'बॉक्स कब्जा / L-Bihari कब्जा (4")'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (5")', 'बॉक्स कब्जा / L-Bihari कब्जा (5")'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (2")', 'लंबा कब्जा / पियानो कब्जा (2")'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (3")', 'लंबा कब्जा / पियानो कब्जा (3")'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (4")', 'लंबा कब्जा / पियानो कब्जा (4")'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (5")', 'लंबा कब्जा / पियानो कब्जा (5")'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (2")', 'पट्टी कब्जा / कमानी कब्जा (2")'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (3")', 'पट्टी कब्जा / कमानी कब्जा (3")'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (4")', 'पट्टी कब्जा / कमानी कब्जा (4")'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (5")', 'पट्टी कब्जा / कमानी कब्जा (5")'),
        ('Door Hardware', 'Chhitkani (3")', 'छिटकनी (3")'),
        ('Door Hardware', 'Chhitkani (4")', 'छिटकनी (4")'),
        ('Door Hardware', 'Chhitkani (6")', 'छिटकनी (6")'),
        ('Door Hardware', 'Chhitkani (8")', 'छिटकनी (8")'),
        ('Door Hardware', 'Chhitkani (10")', 'छिटकनी (10")'),
        ('Door Hardware', 'Chhitkani (12")', 'छिटकनी (12")'),
        ('Door Hardware', 'Aldrop', 'अलड्राप'),
        ('Door Hardware', 'Handle', 'हैंडल'),
        ('Door Hardware', 'Magnet Catcher', 'मैग्नेट कैचर'),
        ('Door Hardware', 'Door Stopper', 'दरवाज़ा रोधक'),
        ('Door Hardware', 'Door Closer (40 Kg)', 'दरवाज़ा Closer (40 किलो तक)'),
        ('Door Hardware', 'Door Closer (60 Kg)', 'दरवाज़ा Closer (60 किलो तक)'),
        ('Door Hardware', 'Door Closer (80 Kg)', 'दरवाज़ा Closer (80 किलो तक)'),
        ('Door Hardware', 'Door Closer (100 Kg)', 'दरवाज़ा Closer (100 किलो तक)'),
        ('Door Hardware', 'Channel / Drawer Channel', 'चैनल / दराज चैनल'),
        ('Door Hardware', 'Hydraulic Pump / Gas Shock', 'हाइड्रोलिक पंप / गैस शॉक'),
        ('Door Hardware', 'Khirki Hook', 'खिड़की हुक'),
        ('Door Hardware', 'Khirki Handle', 'खिड़की हैंडल'),
        ('Door Hardware', 'Aina Clamp / Glass Clip', 'आईना क्लैंप / ग्लास क्लिप'),
        ('Door Hardware', 'Parda Bracket', 'पर्दा ब्रैकेट'),
        ('Door Hardware', 'Parda Chhalla', 'पर्दा Chhalla'),
        ('Door Hardware', 'Heavy Chhitkani', 'भारी छिटकनी'),
        ('Door Hardware', 'Lock (40 mm)', 'ताला (40 मिमी)'),
        ('Door Hardware', 'Lock (50 mm)', 'ताला (50 मिमी)'),
        ('Door Hardware', 'Lock (65 mm)', 'ताला (65 मिमी)'),
        ('Door Hardware', 'Lock (70 mm)', 'ताला (70 मिमी)'),
        ('Door Hardware', 'Lock (75 mm)', 'ताला (75 मिमी)'),
        ('Door Hardware', 'Link Lock (40 mm)', 'लिंक ताला (40 मिमी)'),
        ('Door Hardware', 'Link Lock (50 mm)', 'लिंक ताला (50 मिमी)'),
        ('Door Hardware', 'Link Lock (65 mm)', 'लिंक ताला (65 मिमी)'),
        ('Door Hardware', 'Link Lock (70 mm)', 'लिंक ताला (70 मिमी)'),
        ('Door Hardware', 'Link Lock (75 mm)', 'लिंक ताला (75 मिमी)'),
        ('Door Hardware', 'Konark Lock (40 mm)', 'कोणार्क ताला (40 मिमी)'),
        ('Door Hardware', 'Konark Lock (50 mm)', 'कोणार्क ताला (50 मिमी)'),
        ('Door Hardware', 'Konark Lock (65 mm)', 'कोणार्क ताला (65 मिमी)'),
        ('Door Hardware', 'Konark Lock (70 mm)', 'कोणार्क ताला (70 मिमी)'),
        ('Door Hardware', 'Konark Lock (75 mm)', 'कोणार्क ताला (75 मिमी)'),
        ('Door Hardware', 'Godrej Navtal Lock', 'गोदरेज नवताल ताला'),
        ('Door Hardware', 'Local Lock', 'लोकल ताला'),
        ('Door Hardware', 'Aldrop (4")', 'अलड्राप (4")'),
        ('Door Hardware', 'Aldrop (6")', 'अलड्राप (6")'),
        ('Door Hardware', 'Aldrop (8")', 'अलड्राप (8")'),
        ('Door Hardware', 'Aldrop (10")', 'अलड्राप (10")'),
        ('Door Hardware', 'Aldrop (12")', 'अलड्राप (12")'),
        ('Door Hardware', 'Khirki Handle (2")', 'खिड़की हैंडल (2")'),
        ('Door Hardware', 'Khirki Handle (3")', 'खिड़की हैंडल (3")'),
        ('Door Hardware', 'Khirki Handle (4")', 'खिड़की हैंडल (4")'),
        ('Door Hardware', 'Khirki Handle (6")', 'खिड़की हैंडल (6")'),
        ('Door Hardware', 'Khirki Handle (8")', 'खिड़की हैंडल (8")'),
        ('Door Hardware', 'Khirki Handle (9")', 'खिड़की हैंडल (9")'),
        ('Door Hardware', 'Khirki Handle (10")', 'खिड़की हैंडल (10")'),
        ('Door Hardware', 'Khirki Handle (12")', 'खिड़की हैंडल (12")'),
        ('Door Hardware', 'Parda Bracket (Standard)', 'पर्दा ब्रैकेट (Standard)'),
        ('Door Hardware', 'Parda Bracket (Extendable 4-6")', 'पर्दा ब्रैकेट (Extendable 4-6")'),
        ('Door Hardware', 'Parda Bracket (Extendable 6-10")', 'पर्दा ब्रैकेट (Extendable 6-10")'),
        ('Paints', 'Readymade Putty (1 Kg)', 'Readymade पुट्टी (1 किलो)'),
        ('Paints', 'Readymade Putty (4 Kg)', 'Readymade पुट्टी (4 किलो)'),
        ('Paints', 'Readymade Putty (10 Kg)', 'Readymade पुट्टी (10 किलो)'),
        ('Paints', 'Readymade Putty (20 Kg)', 'Readymade पुट्टी (20 किलो)'),
        ('Paints', 'Interior Primer (1L)', 'आंतरिक भाग प्राइमर (1L)'),
        ('Paints', 'Interior Primer (4L)', 'आंतरिक भाग प्राइमर (4L)'),
        ('Paints', 'Interior Primer (10L)', 'आंतरिक भाग प्राइमर (10L)'),
        ('Paints', 'Interior Primer (20L)', 'आंतरिक भाग प्राइमर (20L)'),
        ('Paints', 'Exterior Primer (1L)', 'बाहरी प्राइमर (1L)'),
        ('Paints', 'Exterior Primer (4L)', 'बाहरी प्राइमर (4L)'),
        ('Paints', 'Exterior Primer (10L)', 'बाहरी प्राइमर (10L)'),
        ('Paints', 'Exterior Primer (20L)', 'बाहरी प्राइमर (20L)'),
        ('Paints', 'Loha Primer / Red Oxide (1L)', 'लोहा प्राइमर / लाल ऑक्साइड (1L)'),
        ('Paints', 'Loha Primer / Red Oxide (4L)', 'लोहा प्राइमर / लाल ऑक्साइड (4L)'),
        ('Paints', 'Loha Primer / Red Oxide (10L)', 'लोहा प्राइमर / लाल ऑक्साइड (10L)'),
        ('Paints', 'Loha Primer / Red Oxide (20L)', 'लोहा प्राइमर / लाल ऑक्साइड (20L)'),
        ('Paints', 'Pila Primer (1L)', 'पीला प्राइमर (1L)'),
        ('Paints', 'Pila Primer (4L)', 'पीला प्राइमर (4L)'),
        ('Paints', 'Pila Primer (10L)', 'पीला प्राइमर (10L)'),
        ('Paints', 'Pila Primer (20L)', 'पीला प्राइमर (20L)'),
        ('Paints', 'Lakri Primer (1L)', 'लकड़ी प्राइमर (1L)'),
        ('Paints', 'Lakri Primer (4L)', 'लकड़ी प्राइमर (4L)'),
        ('Paints', 'Lakri Primer (10L)', 'लकड़ी प्राइमर (10L)'),
        ('Paints', 'Lakri Primer (20L)', 'लकड़ी प्राइमर (20L)'),
        ('Paints', 'Plastic Paint / Emulsion (50ml)', 'प्लास्टिक पेंट / इमल्शन (50मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (100ml)', 'प्लास्टिक पेंट / इमल्शन (100मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (200ml)', 'प्लास्टिक पेंट / इमल्शन (200मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (500ml)', 'प्लास्टिक पेंट / इमल्शन (500मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (1L)', 'प्लास्टिक पेंट / इमल्शन (1L)'),
        ('Paints', 'Plastic Paint / Emulsion (4L)', 'प्लास्टिक पेंट / इमल्शन (4L)'),
        ('Paints', 'Plastic Paint / Emulsion (10L)', 'प्लास्टिक पेंट / इमल्शन (10L)'),
        ('Paints', 'Plastic Paint / Emulsion (20L)', 'प्लास्टिक पेंट / इमल्शन (20L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (50ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (50मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (100ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (100मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (200ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (200मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (500ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (500मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (1L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (1L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (4L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (4L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (10L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (10L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (20L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (20L)'),
        ('Paints', 'Tel Paint / Enamel Paint (50ml)', 'तेल पेंट / इनेमल पेंट (50मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (100ml)', 'तेल पेंट / इनेमल पेंट (100मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (200ml)', 'तेल पेंट / इनेमल पेंट (200मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (500ml)', 'तेल पेंट / इनेमल पेंट (500मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (1L)', 'तेल पेंट / इनेमल पेंट (1L)'),
        ('Paints', 'Tel Paint / Enamel Paint (4L)', 'तेल पेंट / इनेमल पेंट (4L)'),
        ('Paints', 'Tel Paint / Enamel Paint (10L)', 'तेल पेंट / इनेमल पेंट (10L)'),
        ('Paints', 'Tel Paint / Enamel Paint (20L)', 'तेल पेंट / इनेमल पेंट (20L)'),
        ('Paints', 'Stainer (50ml)', 'स्टेनर (50मिली)'),
        ('Paints', 'Stainer (100ml)', 'स्टेनर (100मिली)'),
        ('Paints', 'Stainer (200ml)', 'स्टेनर (200मिली)'),
        ('Paints', 'Stainer (500ml)', 'स्टेनर (500मिली)'),
        ('Paints', 'Stainer (1L)', 'स्टेनर (1L)'),
        ('Paints', 'Stainer (4L)', 'स्टेनर (4L)'),
        ('Paints', 'Stainer (10L)', 'स्टेनर (10L)'),
        ('Paints', 'Stainer (20L)', 'स्टेनर (20L)'),
        ('Paints', 'Tarpeen Tel (50ml)', 'तारपीन तेल (50मिली)'),
        ('Paints', 'Tarpeen Tel (100ml)', 'तारपीन तेल (100मिली)'),
        ('Paints', 'Tarpeen Tel (200ml)', 'तारपीन तेल (200मिली)'),
        ('Paints', 'Tarpeen Tel (500ml)', 'तारपीन तेल (500मिली)'),
        ('Paints', 'Tarpeen Tel (1L)', 'तारपीन तेल (1L)'),
        ('Paints', 'Tarpeen Tel (4L)', 'तारपीन तेल (4L)'),
        ('Paints', 'Tarpeen Tel (10L)', 'तारपीन तेल (10L)'),
        ('Paints', 'Tarpeen Tel (20L)', 'तारपीन तेल (20L)'),
        ('Paints', 'Thinner (50ml)', 'थिनर (50मिली)'),
        ('Paints', 'Thinner (100ml)', 'थिनर (100मिली)'),
        ('Paints', 'Thinner (200ml)', 'थिनर (200मिली)'),
        ('Paints', 'Thinner (500ml)', 'थिनर (500मिली)'),
        ('Paints', 'Thinner (1L)', 'थिनर (1L)'),
        ('Paints', 'Thinner (4L)', 'थिनर (4L)'),
        ('Paints', 'Thinner (10L)', 'थिनर (10L)'),
        ('Paints', 'Thinner (20L)', 'थिनर (20L)'),
        ('Paints', 'Varnish / Polish', 'Varnish / पॉलिश'),
        ('Paints', 'Chana Polish / Gala Polish', 'Chana पॉलिश / Gala पॉलिश'),
        ('Paints', 'Roller Brush', 'रोलर ब्रश'),
        ('Paints', 'Brush (1")', 'ब्रश (1")'),
        ('Paints', 'Brush (1")', 'ब्रश (1")'),
        ('Paints', 'Brush (1")', 'ब्रश (1")'),
        ('Paints', 'Brush (1")', 'ब्रश (1")'),
      
        
        ('Paints', 'Sorish Kagas / Regmar (#80 Number)', 'सरेस कागज़ / रेगमार (#80 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#120 Number)', 'सरेस कागज़ / रेगमार (#120 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#150 Number)', 'सरेस कागज़ / रेगमार (#150 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#220 Number)', 'सरेस कागज़ / रेगमार (#220 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#320 Number)', 'सरेस कागज़ / रेगमार (#320 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#400 Number)', 'सरेस कागज़ / रेगमार (#400 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#600 Number)', 'सरेस कागज़ / रेगमार (#600 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#1000 Number)', 'सरेस कागज़ / रेगमार (#1000 Number)'),
        ('Paints', 'Lakri Regmar (#80 Number)', 'लकड़ी रेगमार (#80 Number)'),
        ('Paints', 'Lakri Regmar (#120 Number)', 'लकड़ी रेगमार (#120 Number)'),
        ('Paints', 'Lakri Regmar (#150 Number)', 'लकड़ी रेगमार (#150 Number)'),
        ('Paints', 'Lakri Regmar (#220 Number)', 'लकड़ी रेगमार (#220 Number)'),
        ('Paints', 'Lakri Regmar (#320 Number)', 'लकड़ी रेगमार (#320 Number)'),
        ('Paints', 'Lakri Regmar (#400 Number)', 'लकड़ी रेगमार (#400 Number)'),
        ('Paints', 'Lakri Regmar (#600 Number)', 'लकड़ी रेगमार (#600 Number)'),
        ('Paints', 'Lakri Regmar (#1000 Number)', 'लकड़ी रेगमार (#1000 Number)'),
        ('Adhesives', 'Fevikwik', 'Fevikwik'),
        ('Paints', 'Silicone Gel Tube', 'सिलिकॉन Gel ट्यूब'),
        ('Paints', 'Silicone Gun', 'सिलिकॉन Gun'),
        ('Paints', 'Araldite ', 'Araldite '),
        ('Paints', 'Foam Spray Tube', 'Foam स्प्रे ट्यूब'),
        ('Paints', 'Regmaal (Grit 80 - Mota)', 'रेगमाल (Grit 80 - Mota)'),
        ('Paints', 'Regmaal (Grit 150 - Madhyam)', 'रेगमाल (Grit 150 - Madhyam)'),
        ('Paints', 'Regmaal (Grit 220 - Baarik)', 'रेगमाल (Grit 220 - Baarik)'),
        ('Paints', 'Geela Regmaal (Grit 400)', 'Geela रेगमाल (Grit 400)'),
        ('Adhesives', 'Masking Tape (0.5")', 'मास्किंग टेप (0.5")'),
        ('Adhesives', 'Masking Tape (1")', 'मास्किंग टेप (1")'),
        ('Adhesives', 'Masking Tape (2")', 'मास्किंग टेप (2")'),
        ('Adhesives', 'Masking Tape (3")', 'मास्किंग टेप (3")'),
        ('Adhesives', 'Fevicol SH (50 g)', 'फेविकोल एसएच (50 ग्राम)'),
        ('Adhesives', 'Fevicol SH (125 g)', 'फेविकोल एसएच (125 ग्राम)'),
        ('Adhesives', 'Fevicol SH (200 g)', 'फेविकोल एसएच (200 ग्राम)'),
        ('Adhesives', 'Fevicol SH (500 g)', 'फेविकोल एसएच (500 ग्राम)'),
        ('Adhesives', 'Fevicol SH (1 Kg)', 'फेविकोल एसएच (1 किलो)'),
        ('Adhesives', 'Fevicol SH (2 Kg)', 'फेविकोल एसएच (2 किलो)'),
        ('Adhesives', 'Fevicol SH (5 Kg)', 'फेविकोल एसएच (5 किलो)'),
        ('Adhesives', 'Fevicol SH (10 Kg)', 'फेविकोल एसएच (10 किलो)'),
        ('Adhesives', 'Fevicol SH (20 Kg)', 'फेविकोल एसएच (20 किलो)'),
        ('Adhesives', 'Fevicol SH (30 Kg)', 'फेविकोल एसएच (30 किलो)'),
        ('Adhesives', 'Fevicol SH (50 Kg)', 'फेविकोल एसएच (50 किलो)'),
        ('Adhesives', 'Fevicol MR (200 g)', 'फेविकोल एमआर (200 ग्राम)'),
        ('Adhesives', 'Fevicol MR (500 g)', 'फेविकोल एमआर (500 ग्राम)'),
        ('Adhesives', 'Fevicol MR (1 Kg)', 'फेविकोल एमआर (1 किलो)'),
        ('Adhesives', 'Fevicol MR (2 Kg)', 'फेविकोल एमआर (2 किलो)'),
        ('Adhesives', 'Fevicol MR (5 Kg)', 'फेविकोल एमआर (5 किलो)'),
        ('Adhesives', 'Fevicol MR (10 Kg)', 'फेविकोल एमआर (10 किलो)'),
        ('Adhesives', 'Fevicol Marine (200 g)', 'फेविकोल मरीन (200 ग्राम)'),
        ('Adhesives', 'Fevicol Marine (500 g)', 'फेविकोल मरीन (500 ग्राम)'),
        ('Adhesives', 'Fevicol Marine (1 Kg)', 'फेविकोल मरीन (1 किलो)'),
        ('Adhesives', 'Fevicol Marine (2 Kg)', 'फेविकोल मरीन (2 किलो)'),
        ('Adhesives', 'Fevicol Marine (5 Kg)', 'फेविकोल मरीन (5 किलो)'),
        ('Adhesives', 'Fevicol Marine (10 Kg)', 'फेविकोल मरीन (10 किलो)'),
        ('Adhesives', 'Fevicol HeatX (200 g)', 'फेविकोल हीटएक्स (200 ग्राम)'),
        ('Adhesives', 'Fevicol HeatX (500 g)', 'फेविकोल हीटएक्स (500 ग्राम)'),
        ('Adhesives', 'Fevicol HeatX (1 Kg)', 'फेविकोल हीटएक्स (1 किलो)'),
        ('Adhesives', 'Fevicol HeatX (2 Kg)', 'फेविकोल हीटएक्स (2 किलो)'),
        ('Adhesives', 'Fevicol HeatX (5 Kg)', 'फेविकोल हीटएक्स (5 किलो)'),
        ('Adhesives', 'Fevicol HeatX (10 Kg)', 'फेविकोल हीटएक्स (10 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (200 g)', 'फेविकोल फास्ट टैक (200 ग्राम)'),
        ('Adhesives', 'Fevicol Fast Tack (500 g)', 'फेविकोल फास्ट टैक (500 ग्राम)'),
        ('Adhesives', 'Fevicol Fast Tack (1 Kg)', 'फेविकोल फास्ट टैक (1 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (2 Kg)', 'फेविकोल फास्ट टैक (2 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (5 Kg)', 'फेविकोल फास्ट टैक (5 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (10 Kg)', 'फेविकोल फास्ट टैक (10 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (200 g)', 'फेविकोल नेल फ्री अल्ट्रा (200 ग्राम)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (500 g)', 'फेविकोल नेल फ्री अल्ट्रा (500 ग्राम)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (1 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (1 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (2 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (2 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (5 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (5 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (10 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (10 किलो)'),
        ('Electrical', 'Bijli Tape', 'बिजली टेप'),
        ('Farmer/Agricultural Tools', 'Kudal', ' कुदाल'),
        ('Farmer/Agricultural Tools', 'Belcha', 'बेलचा'),
        ('Farmer/Agricultural Tools', 'Gainti', 'Gainti'),
        ('Farmer/Agricultural Tools', 'Kulhari', 'Kulhari'),
        ('Farmer/Agricultural Tools', 'Tasla', 'तसला'),
        ('Farmer/Agricultural Tools', 'Tagari', 'तगारी'),
   
        ('Farmer/Agricultural Tools', 'Rassi / Nylon Rassi', 'रस्सी / नायलॉन रस्सी'),
        ('Farmer/Agricultural Tools', 'Sutli', 'सुतली'),
        ('Handpump (Chapakal) Parts', 'Handpump (No. 4)', 'चापाकल (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Silinder (No. 4)', 'हैंडपंप सिलेंडर (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Bucket / Leather (No. 4")', 'हैंडपंप बकेट / लेदर (नंबर 4")'),
        ('Handpump (Chapakal) Parts', 'Handpump Bucket / Leather (No. 6")', 'हैंडपंप बकेट / लेदर (नंबर 6")'),
        ('Handpump (Chapakal) Parts', 'Handpump Bucket / Plastic (No. 4")', 'हैंडपंप बकेट / प्लास्टिक (नंबर 4")'),
        ('Handpump (Chapakal) Parts', 'Handpump Valve (No. 4)', 'हैंडपंप वाल्व (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Valve Weight (No. 4)', 'हैंडपंप वाल्व वेट (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Plunger (No. 4)', 'हैंडपंप प्लंजर (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Plunger (No. 6)', 'हैंडपंप प्लंजर (नंबर 6)'),

        ('Handpump (Chapakal) Parts', 'Handpump Handle (No. 4)', 'हैंडपंप हैंडल (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Handle (No. 6)', 'हैंडपंप हैंडल (नंबर 6)'),

        ('Handpump (Chapakal) Parts', 'Handpump Topi (No. 4)', 'हैंडपंप टोपी (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Topi (No. 6)', 'हैंडपंप टोपी (नंबर 6)'),
        ('Handpump (Chapakal) Parts', 'Handpump Thali (No. 4)', 'हैंडपंप थाली (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Thali (No. 6)', 'हैंडपंप थाली (नंबर 6)'),
 
        ('Farmer/Agricultural Tools', 'Water Pump', 'पानी पंप'),
        ('Farmer/Agricultural Tools', 'Tirpal', 'तिरपाल'),

        ('Farmer/Agricultural Tools', 'Hal', 'हल'),
        ('Farmer/Agricultural Tools', 'Jua', 'जुआ'),
        ('Farmer/Agricultural Tools', 'Hansiya (Chhota)', 'हंसिया (Chhota)'),
        ('Farmer/Agricultural Tools', 'Hasua (Bada)', 'हसुआ (Bada)'),
        ('Farmer/Agricultural Tools', 'Khurpi', 'खुरपी'),
        ('Farmer/Agricultural Tools', 'Kudal (No. 1)', 'कुदाल (नंबर 1)'),
        ('Farmer/Agricultural Tools', 'Kudal (No. 2)', 'कुदाल (नंबर 2)'),
        ('Farmer/Agricultural Tools', 'Belcha / Fawda (No. 6)', 'बेलचा / फावड़ा (नंबर 6)'),
        ('Farmer/Agricultural Tools', 'Belcha / Fawda (No. 8)', 'बेलचा / फावड़ा (नंबर 8)'),
        ('Farmer/Agricultural Tools', 'Gaiti (3 lb)', 'गैंती (3 पाउंड)'),
        ('Farmer/Agricultural Tools', 'Gaiti (5 lb)', 'गैंती (5 पाउंड)'),
        ('Farmer/Agricultural Tools', 'Soop', 'सूप'),
        ('Farmer/Agricultural Tools', 'Tokri', 'टोकरी'),
        ('Farmer/Agricultural Tools', 'Chalni (Baarik/Mota)', 'छलनी (Baarik/Mota)'),
        ('Farmer/Agricultural Tools', 'Spray Pump (16 Ltr)', 'स्प्रे पंप (16 Ltr)'),
        ('Farmer/Agricultural Tools', 'Spray Pump (18 Ltr)', 'स्प्रे पंप (18 Ltr)'),
        ('Farmer/Agricultural Tools', 'Khaad Kaanta', 'खाद कांटा'),
        ('Farmer/Agricultural Tools', 'Saan Patthar', 'सान पत्थर'),
        ('Farmer/Agricultural Tools', 'Daranti', 'दरांती'),
        ('Safety Items', 'Welding Rod / Ranga', 'वेल्डिंग Rod / Ranga'),
        ('Safety Items', 'Welding Kagas / Aina', 'वेल्डिंग कागज़ / आईना'),
        ('Safety Items', 'Safety Cap / Topi', 'सेफ्टी Cap / Topi'),
        ('Safety Items', 'Kapde Ka Hand-Glove', 'Kapde का Hand-Glove'),
        ('Safety Items', 'Rubber Glove', 'Rubber Glove'),
        ('Safety Items', 'Safety Chashma', 'सेफ्टी Chashma'),
        ('Safety Items', 'Mask', 'Mask'),

        ('Measuring/Misc', 'Machine Tel / Mobil Oil', 'मशीन तेल / Mobil Oil'),
        ('Measuring/Misc', 'Grease (10 g)', ' ग्रीस (10 ग्राम)'),
        ('Measuring/Misc', 'Grease (20 g)', ' ग्रीस (20 ग्राम)'),
        ('Measuring/Misc', 'Grease (50 g)', ' ग्रीस (50 ग्राम)'),
        ('Measuring/Misc', 'Grease (100 g)', ' ग्रीस (100 ग्राम)'),
        ('Measuring/Misc', 'Grease (200 g)', ' ग्रीस (200 ग्राम)'),
        ('Measuring/Misc', 'Grease (500 g)', ' ग्रीस (500 ग्राम)'),
        ('Measuring/Misc', 'Grease (1 kg)', ' ग्रीस (1 किलो)'),
        ('Measuring/Misc', 'Lakri Beading / Gola', 'लकड़ी Beading / Gola'),
        ('Measuring/Misc', 'Machine Belt / V-Belt', 'मशीन Belt / V-Belt'),
        ('Measuring/Misc', 'Chakka', 'चक्का'),
        ('Measuring/Misc', 'Loha Junna / Steel Wool', 'लोहा Junna / स्टील Wool'),
        ('Fasteners', 'Pin Kati (0.5")', 'पिन कटी (0.5")'),
        ('Fasteners', 'Pin Kati (0.75")', 'पिन कटी (0.75")'),
        ('Fasteners', 'Pin Kati (1")', 'पिन कटी (1")'),
        ('Fasteners', 'Pin Kati (1.5")', 'पिन कटी (1.5")'),
        ('Fasteners', 'Pin Kati (2")', 'पिन कटी (2")'),
        ('Hand Tools', 'Putty Patti (2")', 'पुट्टी पैटी (2")'),
        ('Hand Tools', 'Putty Patti (3")', 'पुट्टी पैटी (3")'),
        ('Hand Tools', 'Putty Patti (4")', 'पुट्टी पैटी (4")'),
        ('Hand Tools', 'Putty Patti (6")', 'पुट्टी पैटी (6")'),
        ('Plumbing', 'Check Valve (0.5")', 'चेक वाल्व (0.5")'),
        ('Plumbing', 'Check Valve (0.75")', 'चेक वाल्व (0.75")'),
        ('Plumbing', 'Check Valve (1")', 'चेक वाल्व (1")'),
        ('Plumbing', 'Check Valve (1.25")', 'चेक वाल्व (1.25")'),
        ('Plumbing', 'Check Valve (1.5")', 'चेक वाल्व (1.5")'),
        ('Plumbing', 'Check Valve (2")', 'चेक वाल्व (2")'),
        ('Plumbing', 'Loha Check Valve (0.5")', 'लोहा चेक वाल्व (0.5")'),
        ('Plumbing', 'Loha Check Valve (0.75")', 'लोहा चेक वाल्व (0.75")'),
        ('Plumbing', 'Loha Check Valve (1")', 'लोहा चेक वाल्व (1")'),
        ('Plumbing', 'Loha Check Valve (1.5")', 'लोहा चेक वाल्व (1.5")'),
        ('Plumbing', 'Loha Check Valve (2")', 'लोहा चेक वाल्व (2")'),
        ('Plumbing', 'Ball Valve / Chabi (0.5")', 'बॉल वाल्व (0.5")'),
        ('Plumbing', 'Ball Valve / Chabi (0.75")', 'बॉल वाल्व (0.75")'),
        ('Plumbing', 'Ball Valve / Chabi (1")', 'बॉल वाल्व (1")'),
        ('Plumbing', 'Ball Valve / Chabi (1.25")', 'बॉल वाल्व (1.25")'),
        ('Plumbing', 'Ball Valve / Chabi (1.5")', 'बॉल वाल्व (1.5")'),
        ('Plumbing', 'Ball Valve / Chabi (2")', 'बॉल वाल्व (2")'),
        ('Plumbing', 'Loha Ball Valve (0.5")', 'लोहा बॉल वाल्व (0.5")'),
        ('Plumbing', 'Loha Ball Valve (0.75")', 'लोहा बॉल वाल्व (0.75")'),
        ('Plumbing', 'Loha Ball Valve (1")', 'लोहा बॉल वाल्व (1")'),
        ('Plumbing', 'Loha Ball Valve (1.5")', 'लोहा बॉल वाल्व (1.5")'),
        ('Plumbing', 'Loha Ball Valve (2")', 'लोहा बॉल वाल्व (2")'),
        ('Plumbing', 'PVC Ball Valve (0.5")', 'पीवीसी बॉल वाल्व (0.5")'),
        ('Plumbing', 'PVC Ball Valve (0.75")', 'पीवीसी बॉल वाल्व (0.75")'),
        ('Plumbing', 'PVC Ball Valve (1")', 'पीवीसी बॉल वाल्व (1")'),
        ('Plumbing', 'PVC Ball Valve (1.5")', 'पीवीसी बॉल वाल्व (1.5")'),
        ('Plumbing', 'PVC Ball Valve (2")', 'पीवीसी बॉल वाल्व (2")'),
        ('Fasteners', 'Carriage Bolt (2 Suta / M6, 1.5")', 'गोल सिर बोल्ट (2 सूता, 1.5")'),
        ('Fasteners', 'Carriage Bolt (2 Suta / M6, 2")', 'गोल सिर बोल्ट (2 सूता, 2")'),
        ('Fasteners', 'Carriage Bolt (2.5 Suta / M8, 2")', 'गोल सिर बोल्ट (2.5 सूता, 2")'),
        ('Fasteners', 'Carriage Bolt (2.5 Suta / M8, 3")', 'गोल सिर बोल्ट (2.5 सूता, 3")'),
        ('Fasteners', 'Carriage Bolt (3 Suta / M10, 3")', 'गोल सिर बोल्ट (3 सूता, 3")'),
        ('Fasteners', 'Carriage Bolt (3 Suta / M10, 4")', 'गोल सिर बोल्ट (3 सूता, 4")'),
        ('Fasteners', 'Carriage Bolt (4 Suta / M12, 4")', 'गोल सिर बोल्ट (4 सूता, 4")'),
        ('Farmer/Agricultural Tools', 'Gamla (8")', 'गमला (8")'),
        ('Farmer/Agricultural Tools', 'Gamla (10")', 'गमला (10")'),
        ('Farmer/Agricultural Tools', 'Gamla (12")', 'गमला (12")'),
        ('Farmer/Agricultural Tools', 'Gamla (14")', 'गमला (14")'),
        ('Farmer/Agricultural Tools', 'Gamla (16")', 'गमला (16")'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (10")', 'सीमेंट गमला (10")'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (12")', 'सीमेंट गमला (12")'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (14")', 'सीमेंट गमला (14")'),
        ('Farmer/Agricultural Tools', 'GI Tagari (12")', 'जीआई तगारी (12")'),
        ('Farmer/Agricultural Tools', 'GI Tagari (14")', 'जीआई तगारी (14")'),
        ('Farmer/Agricultural Tools', 'GI Tagari (16")', 'जीआई तगारी (16")'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (12")', 'प्लास्टिक तगारी (12")'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (14")', 'प्लास्टिक तगारी (14")'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (16")', 'प्लास्टिक तगारी (16")'),
        ('Door Hardware', 'Link Mortise Lock', 'Link मोर्टिस लॉक'),
        ('Door Hardware', 'Konark Mortise Lock', 'Konark मोर्टिस लॉक'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe (0.75")', 'प्रेशर पाइप (0.75")'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe (1")', 'प्रेशर पाइप (1")'),
        ('Farmer/Agricultural Tools', 'Jointer (0.75")', 'जॉइंटर (0.75")'),
        ('Farmer/Agricultural Tools', 'Jointer (1")', 'जॉइंटर (1")'),
        ('Door Hardware', 'Koniya (1")', 'कोनिया (1")'),
        ('Door Hardware', 'Koniya (1.5")', 'कोनिया (1.5")'),
        ('Door Hardware', 'Koniya (2")', 'कोनिया (2")'),
        ('Door Hardware', 'Koniya (3")', 'कोनिया (3")'),
        ('Door Hardware', 'Koniya (4")', 'कोनिया (4")'),
        ('Building Materials', 'Kirmichi (500 g)', 'किरमिची (500 ग्राम)'),
        ('Building Materials', 'Kirmichi (1 kg)', 'किरमिची (1 किलो)'),
        ('Building Materials', 'Kirmichi (5 kg)', 'किरमिची (5 किलो)'),
        ('Building Materials', 'Kirmichi (25 kg)', 'किरमिची (25 किलो)'),
        ('Hand Tools', 'Gurmala (9")', 'गुरमाला (9")'),
        ('Hand Tools', 'Gurmala (10")', 'गुरमाला (10")'),
        ('Hand Tools', 'Gurmala (12")', 'गुरमाला (12")'),
        ('Hand Tools', 'Gurmala (14")', 'गुरमाला (14")'),
    
        ('Hand Tools', 'Measuring Tape (3m)', 'इंची टेप  (3m)'),
        ('Hand Tools', 'Measuring Tape (5m)', 'इंची टेप (5m)'),
        ('Hand Tools', 'Feeta (10m)', 'फीता (10m)'),
        ('Hand Tools', 'Feeta (50m)', 'फीता (50m)'),
        ('Hand Tools', 'Feeta (100m)', 'फीता (100m)')

        ('Power Tools', 'Wall Cutter Wheel (4")', 'वॉल कटर व्हील (4")'),
        ('Power Tools', 'Wall Cutter Wheel (5")', 'वॉल कटर व्हील (5")'),
        ('Power Tools', 'Wall Cutter Wheel (14")', 'वॉल कटर व्हील (14")'),
        ('Power Tools', 'Tile Cutter Wheel (4")', 'टाइल कटर व्हील (4")'),
        ('Power Tools', 'Tile Cutter Wheel (5")', 'टाइल कटर व्हील (5")'),
        ('Power Tools', 'Tile Cutter Wheel (14")', 'टाइल कटर व्हील (14")'),
        ('Power Tools', 'Iron Cutter Wheel (4")', 'लोहा कटर व्हील (4")'),
        ('Power Tools', 'Iron Cutter Wheel (5")', 'लोहा कटर व्हील (5")'),
        ('Power Tools', 'Iron Cutter Wheel (14")', 'लोहा कटर व्हील (14")'),
        ('Farmer/Agricultural Tools', 'Water Pump (0.5 HP)', 'पानी पंप (0.5 HP)'),
        ('Farmer/Agricultural Tools', 'Water Pump (1 HP)', 'पानी पंप (1 HP)'),
        ('Farmer/Agricultural Tools', 'Water Pump (1.5 HP)', 'पानी पंप (1.5 HP)'),
        ('Farmer/Agricultural Tools', 'Water Pump (2 HP)', 'पानी पंप (2 HP)'),
        ('Farmer/Agricultural Tools', 'Water Pump (3 HP)', 'पानी पंप (3 HP)'),
        ('Farmer/Agricultural Tools', 'Water Pump (5 HP)', 'पानी पंप (5 HP)'),
    ) AS seed(category_name, name_en, name_hi)
JOIN categories c
  ON LOWER(c.name_en) = LOWER(seed.category_name);

COMMIT;

-- Verification:
-- SELECT COUNT(*) FROM products;
-- SELECT COUNT(DISTINCT category_id) FROM products;
-- SELECT c.name_en, COUNT(*)
-- FROM products p
-- JOIN categories c ON c.id = p.category_id
-- GROUP BY c.name_en
-- ORDER BY c.name_en;
