-- 007_seed_bihar_hardware_catalogue.sql
-- Final clean product catalogue seed.
-- Source: bihar_hardware_bilingual_with_size_v9.csv
-- Product rows: 1,060
--
-- Product mapping:
--   Transliteration (Roman, with Size) -> products.name_en
--   Product Name (Local/Hindi, with Size) -> products.name_hi
--   Packing/Unit -> ignored
--   unit_id -> NULL
--   brand -> NULL
--
-- Existing category mapping:
--   Fasteners & Fixings       -> Fasteners
--   Building Materials        -> Building Materials
--   Hand Tools                -> Hand Tools
--   Power Tools               -> Power Tools
--   Plumbing & Sanitary       -> Plumbing
--   Architectural Hardware    -> Door Hardware
--   Electrical Goods          -> Electrical
--   Agricultural & Rural Tools -> Farmer/Agricultural Tools
--   Agricultural handpump rows -> Handpump (Chapakal) Parts
--   Paints & Adhesives        -> Paints / Adhesives based on product name
--   Safety & Misc Essentials  -> Safety Items / Measuring/Misc based on product name

BEGIN;

-- Replace the old product catalogue.
DELETE FROM products;

INSERT INTO products (
    name_en,
    name_hi,
    category_id,
    unit_id,
    brand,
    status
)
SELECT
    seed.name_en,
    seed.name_hi,
    c.id,
    NULL,
    NULL,
    'active'
FROM (
    VALUES
        ('Fasteners', 'Kati (0.5 inch)', 'Kati (0.5 इंच)'),
        ('Fasteners', 'Kati (1 inch)', 'Kati (1 इंच)'),
        ('Fasteners', 'Kati (1.5 inch)', 'Kati (1.5 इंच)'),
        ('Fasteners', 'Kati (2 inch)', 'Kati (2 इंच)'),
        ('Fasteners', 'Kati (2.5 inch)', 'Kati (2.5 इंच)'),
        ('Fasteners', 'Kati (3 inch)', 'Kati (3 इंच)'),
        ('Fasteners', 'Kati (4 inch)', 'Kati (4 इंच)'),
        ('Fasteners', 'Dewal Kati (0.5 inch)', 'दीवाल Kati (0.5 इंच)'),
        ('Fasteners', 'Dewal Kati (1 inch)', 'दीवाल Kati (1 इंच)'),
        ('Fasteners', 'Dewal Kati (1.5 inch)', 'दीवाल Kati (1.5 इंच)'),
        ('Fasteners', 'Dewal Kati (2 inch)', 'दीवाल Kati (2 इंच)'),
        ('Fasteners', 'Dewal Kati (2.5 inch)', 'दीवाल Kati (2.5 इंच)'),
        ('Fasteners', 'Dewal Kati (3 inch)', 'दीवाल Kati (3 इंच)'),
        ('Fasteners', 'Dewal Kati (4 inch)', 'दीवाल Kati (4 इंच)'),
        ('Fasteners', 'Pech (19x6)', 'पेच (19x6)'),
        ('Fasteners', 'Pech (25x8)', 'पेच (25x8)'),
        ('Fasteners', 'Pech (35x8)', 'पेच (35x8)'),
        ('Fasteners', 'Pech (50x8)', 'पेच (50x8)'),
        ('Fasteners', 'Pech (75x10)', 'पेच (75x10)'),
        ('Fasteners', 'Gypsum Pech (19x6)', 'जिप्सम पेच (19x6)'),
        ('Fasteners', 'Gypsum Pech (25x8)', 'जिप्सम पेच (25x8)'),
        ('Fasteners', 'Gypsum Pech (35x8)', 'जिप्सम पेच (35x8)'),
        ('Fasteners', 'Gypsum Pech (50x8)', 'जिप्सम पेच (50x8)'),
        ('Fasteners', 'Gypsum Pech (75x10)', 'जिप्सम पेच (75x10)'),
        ('Fasteners', 'Gitti', 'गिट्टी'),
        ('Fasteners', 'Gullu / Stud', 'गुल्लू / स्टड'),
        ('Fasteners', 'Dash Fastener', 'डैश फास्टनर'),
        ('Fasteners', 'Rivet Kati', 'रिवेट Kati'),
        ('Fasteners', 'Self-Star Pech (19x6)', 'Self-स्टार पेच (19x6)'),
        ('Fasteners', 'Self-Star Pech (25x8)', 'Self-स्टार पेच (25x8)'),
        ('Fasteners', 'Self-Star Pech (35x8)', 'Self-स्टार पेच (35x8)'),
        ('Fasteners', 'Self-Star Pech (50x8)', 'Self-स्टार पेच (50x8)'),
        ('Fasteners', 'Self-Star Pech (75x10)', 'Self-स्टार पेच (75x10)'),
        ('Fasteners', 'Gullu / Stud (M6)', 'गुल्लू / स्टड (M6)'),
        ('Fasteners', 'Gullu / Stud (M8)', 'गुल्लू / स्टड (M8)'),
        ('Fasteners', 'Gullu / Stud (M10)', 'गुल्लू / स्टड (M10)'),
        ('Fasteners', 'Gullu / Stud (M12)', 'गुल्लू / स्टड (M12)'),
        ('Fasteners', 'Gullu / Stud (M16)', 'गुल्लू / स्टड (M16)'),
        ('Fasteners', 'Gullu / Stud (M20)', 'गुल्लू / स्टड (M20)'),
        ('Fasteners', 'Machine Screw (19x6 mm)', 'मशीन स्क्रू (19x6 मिमी)'),
        ('Fasteners', 'Machine Screw (25x8 mm)', 'मशीन स्क्रू (25x8 मिमी)'),
        ('Fasteners', 'Machine Screw (35x8 mm)', 'मशीन स्क्रू (35x8 मिमी)'),
        ('Fasteners', 'Machine Screw (50x8 mm)', 'मशीन स्क्रू (50x8 मिमी)'),
        ('Fasteners', 'Machine Screw (75x10 mm)', 'मशीन स्क्रू (75x10 मिमी)'),
        ('Fasteners', 'Bolt (2 Suta / M6)', 'बोल्ट (2 सूता / M6)'),
        ('Fasteners', 'Bolt (2.5 Suta / M8)', 'बोल्ट (2.5 सूता / M8)'),
        ('Fasteners', 'Bolt (3 Suta / M10)', 'बोल्ट (3 सूता / M10)'),
        ('Fasteners', 'Bolt (4 Suta / M12)', 'बोल्ट (4 सूता / M12)'),
        ('Fasteners', 'Bolt (5 Suta / M16)', 'बोल्ट (5 सूता / M16)'),
        ('Fasteners', 'Bolt (6 Suta / M20)', 'बोल्ट (6 सूता / M20)'),
        ('Fasteners', 'GI Bolt (2 Suta / M6)', 'GI बोल्ट (2 सूता / M6)'),
        ('Fasteners', 'GI Bolt (2.5 Suta / M8)', 'GI बोल्ट (2.5 सूता / M8)'),
        ('Fasteners', 'GI Bolt (3 Suta / M10)', 'GI बोल्ट (3 सूता / M10)'),
        ('Fasteners', 'GI Bolt (4 Suta / M12)', 'GI बोल्ट (4 सूता / M12)'),
        ('Fasteners', 'GI Bolt (5 Suta / M16)', 'GI बोल्ट (5 सूता / M16)'),
        ('Fasteners', 'GI Bolt (6 Suta / M20)', 'GI बोल्ट (6 सूता / M20)'),
        ('Fasteners', 'Chadar Bolt', 'चादर बोल्ट'),
        ('Fasteners', 'U-Bolt', 'U-बोल्ट'),
        ('Fasteners', 'J-Bolt (6 inch)', 'J-बोल्ट (6 इंच)'),
        ('Fasteners', 'J-Bolt (8 inch)', 'J-बोल्ट (8 इंच)'),
        ('Fasteners', 'J-Bolt (9 inch)', 'J-बोल्ट (9 इंच)'),
        ('Fasteners', 'J-Bolt (10 inch)', 'J-बोल्ट (10 इंच)'),
        ('Fasteners', 'J-Bolt (12 inch)', 'J-बोल्ट (12 इंच)'),
        ('Fasteners', 'Nut (2 Suta / M6)', 'नट (2 सूता / M6)'),
        ('Fasteners', 'Nut (2.5 Suta / M8)', 'नट (2.5 सूता / M8)'),
        ('Fasteners', 'Nut (3 Suta / M10)', 'नट (3 सूता / M10)'),
        ('Fasteners', 'Nut (4 Suta / M12)', 'नट (4 सूता / M12)'),
        ('Fasteners', 'Nut (5 Suta / M16)', 'नट (5 सूता / M16)'),
        ('Fasteners', 'Nut (6 Suta / M20)', 'नट (6 सूता / M20)'),
        ('Fasteners', 'GI Nut (2 Suta / M6)', 'GI नट (2 सूता / M6)'),
        ('Fasteners', 'GI Nut (2.5 Suta / M8)', 'GI नट (2.5 सूता / M8)'),
        ('Fasteners', 'GI Nut (3 Suta / M10)', 'GI नट (3 सूता / M10)'),
        ('Fasteners', 'GI Nut (4 Suta / M12)', 'GI नट (4 सूता / M12)'),
        ('Fasteners', 'GI Nut (5 Suta / M16)', 'GI नट (5 सूता / M16)'),
        ('Fasteners', 'GI Nut (6 Suta / M20)', 'GI नट (6 सूता / M20)'),
        ('Fasteners', 'Waser (2 Suta / M6)', 'वाशर (2 सूता / M6)'),
        ('Fasteners', 'Waser (2.5 Suta / M8)', 'वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'Waser (3 Suta / M10)', 'वाशर (3 सूता / M10)'),
        ('Fasteners', 'Waser (4 Suta / M12)', 'वाशर (4 सूता / M12)'),
        ('Fasteners', 'Waser (5 Suta / M16)', 'वाशर (5 सूता / M16)'),
        ('Fasteners', 'Waser (6 Suta / M20)', 'वाशर (6 सूता / M20)'),
        ('Fasteners', 'GI Waser (2 Suta / M6)', 'GI वाशर (2 सूता / M6)'),
        ('Fasteners', 'GI Waser (2.5 Suta / M8)', 'GI वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'GI Waser (3 Suta / M10)', 'GI वाशर (3 सूता / M10)'),
        ('Fasteners', 'GI Waser (4 Suta / M12)', 'GI वाशर (4 सूता / M12)'),
        ('Fasteners', 'GI Waser (5 Suta / M16)', 'GI वाशर (5 सूता / M16)'),
        ('Fasteners', 'GI Waser (6 Suta / M20)', 'GI वाशर (6 सूता / M20)'),
        ('Fasteners', 'Spring Waser (2 Suta / M6)', 'स्प्रिंग वाशर (2 सूता / M6)'),
        ('Fasteners', 'Spring Waser (2.5 Suta / M8)', 'स्प्रिंग वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'Spring Waser (3 Suta / M10)', 'स्प्रिंग वाशर (3 सूता / M10)'),
        ('Fasteners', 'Spring Waser (4 Suta / M12)', 'स्प्रिंग वाशर (4 सूता / M12)'),
        ('Fasteners', 'Spring Waser (5 Suta / M16)', 'स्प्रिंग वाशर (5 सूता / M16)'),
        ('Fasteners', 'Spring Waser (6 Suta / M20)', 'स्प्रिंग वाशर (6 सूता / M20)'),
        ('Fasteners', 'GI Spring Waser (2 Suta / M6)', 'GI स्प्रिंग वाशर (2 सूता / M6)'),
        ('Fasteners', 'GI Spring Waser (2.5 Suta / M8)', 'GI स्प्रिंग वाशर (2.5 सूता / M8)'),
        ('Fasteners', 'GI Spring Waser (3 Suta / M10)', 'GI स्प्रिंग वाशर (3 सूता / M10)'),
        ('Fasteners', 'GI Spring Waser (4 Suta / M12)', 'GI स्प्रिंग वाशर (4 सूता / M12)'),
        ('Fasteners', 'GI Spring Waser (5 Suta / M16)', 'GI स्प्रिंग वाशर (5 सूता / M16)'),
        ('Fasteners', 'GI Spring Waser (6 Suta / M20)', 'GI स्प्रिंग वाशर (6 सूता / M20)'),
        ('Building Materials', 'Chhar / Sariya (8mm)', 'छड़ / सरिया (8मिमी)'),
        ('Building Materials', 'Chhar / Sariya (10mm)', 'छड़ / सरिया (10मिमी)'),
        ('Building Materials', 'Chhar / Sariya (12mm)', 'छड़ / सरिया (12मिमी)'),
        ('Building Materials', 'Chhar / Sariya (16mm)', 'छड़ / सरिया (16मिमी)'),
        ('Building Materials', 'Chhar / Sariya (20mm)', 'छड़ / सरिया (20मिमी)'),
        ('Building Materials', 'Chhar / Sariya (25mm)', 'छड़ / सरिया (25मिमी)'),
        ('Building Materials', 'Cement Bori', 'सीमेंट बोरी'),
        ('Building Materials', 'White Cement', 'सफेद सीमेंट'),
        ('Building Materials', 'Loha Chadar', 'लोहा चादर'),
        ('Building Materials', 'Cement Chadar', 'सीमेंट चादर'),
        ('Building Materials', 'Plastic Chadar', 'प्लास्टिक चादर'),
        ('Building Materials', 'Kantedar Tar', 'कांटेदार तार'),
        ('Building Materials', 'Jali Tar (2x2 inch, 3 ft, 12 SWG)', 'जाली तार (2x2 इंच, 3 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 3 ft, 14 SWG)', 'जाली तार (2x2 इंच, 3 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 4 ft, 12 SWG)', 'जाली तार (2x2 इंच, 4 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 4 ft, 14 SWG)', 'जाली तार (2x2 इंच, 4 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 5 ft, 12 SWG)', 'जाली तार (2x2 इंच, 5 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 5 ft, 14 SWG)', 'जाली तार (2x2 इंच, 5 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 6 ft, 12 SWG)', 'जाली तार (2x2 इंच, 6 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (2x2 inch, 6 ft, 14 SWG)', 'जाली तार (2x2 इंच, 6 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 3 ft, 12 SWG)', 'जाली तार (3x3 इंच, 3 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 3 ft, 14 SWG)', 'जाली तार (3x3 इंच, 3 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 4 ft, 12 SWG)', 'जाली तार (3x3 इंच, 4 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 4 ft, 14 SWG)', 'जाली तार (3x3 इंच, 4 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 5 ft, 12 SWG)', 'जाली तार (3x3 इंच, 5 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 5 ft, 14 SWG)', 'जाली तार (3x3 इंच, 5 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 6 ft, 12 SWG)', 'जाली तार (3x3 इंच, 6 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (3x3 inch, 6 ft, 14 SWG)', 'जाली तार (3x3 इंच, 6 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 3 ft, 12 SWG)', 'जाली तार (4x4 इंच, 3 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 3 ft, 14 SWG)', 'जाली तार (4x4 इंच, 3 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 4 ft, 12 SWG)', 'जाली तार (4x4 इंच, 4 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 4 ft, 14 SWG)', 'जाली तार (4x4 इंच, 4 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 5 ft, 12 SWG)', 'जाली तार (4x4 इंच, 5 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 5 ft, 14 SWG)', 'जाली तार (4x4 इंच, 5 फीट, 14 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 6 ft, 12 SWG)', 'जाली तार (4x4 इंच, 6 फीट, 12 SWG)'),
        ('Building Materials', 'Jali Tar (4x4 inch, 6 ft, 14 SWG)', 'जाली तार (4x4 इंच, 6 फीट, 14 SWG)'),
        ('Building Materials', 'Murgi Jali (0.5 inch, 2 ft x 30 m)', 'मुर्गी जाली (0.5 इंच, 2 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (0.5 inch, 3 ft x 30 m)', 'मुर्गी जाली (0.5 इंच, 3 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (0.5 inch, 4 ft x 30 m)', 'मुर्गी जाली (0.5 इंच, 4 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (0.5 inch, 5 ft x 30 m)', 'मुर्गी जाली (0.5 इंच, 5 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (0.5 inch, 6 ft x 30 m)', 'मुर्गी जाली (0.5 इंच, 6 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (1 inch, 2 ft x 30 m)', 'मुर्गी जाली (1 इंच, 2 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (1 inch, 3 ft x 30 m)', 'मुर्गी जाली (1 इंच, 3 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (1 inch, 4 ft x 30 m)', 'मुर्गी जाली (1 इंच, 4 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (1 inch, 5 ft x 30 m)', 'मुर्गी जाली (1 इंच, 5 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (1 inch, 6 ft x 30 m)', 'मुर्गी जाली (1 इंच, 6 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (2 inch, 2 ft x 30 m)', 'मुर्गी जाली (2 इंच, 2 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (2 inch, 3 ft x 30 m)', 'मुर्गी जाली (2 इंच, 3 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (2 inch, 4 ft x 30 m)', 'मुर्गी जाली (2 इंच, 4 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (2 inch, 5 ft x 30 m)', 'मुर्गी जाली (2 इंच, 5 फीट x 30 मी)'),
        ('Building Materials', 'Murgi Jali (2 inch, 6 ft x 30 m)', 'मुर्गी जाली (2 इंच, 6 फीट x 30 मी)'),
        ('Building Materials', 'Chatai Jali (0.5x0.5 inch, 3 ft)', 'चटाई जाली (0.5x0.5 इंच, 3 फीट)'),
        ('Building Materials', 'Chatai Jali (0.5x0.5 inch, 4 ft)', 'चटाई जाली (0.5x0.5 इंच, 4 फीट)'),
        ('Building Materials', 'Chatai Jali (0.5x0.5 inch, 5 ft)', 'चटाई जाली (0.5x0.5 इंच, 5 फीट)'),
        ('Building Materials', 'Chatai Jali (0.5x0.5 inch, 6 ft)', 'चटाई जाली (0.5x0.5 इंच, 6 फीट)'),
        ('Building Materials', 'Chatai Jali (1x1 inch, 3 ft)', 'चटाई जाली (1x1 इंच, 3 फीट)'),
        ('Building Materials', 'Chatai Jali (1x1 inch, 4 ft)', 'चटाई जाली (1x1 इंच, 4 फीट)'),
        ('Building Materials', 'Chatai Jali (1x1 inch, 5 ft)', 'चटाई जाली (1x1 इंच, 5 फीट)'),
        ('Building Materials', 'Chatai Jali (1x1 inch, 6 ft)', 'चटाई जाली (1x1 इंच, 6 फीट)'),
        ('Building Materials', 'Chatai Jali (2x2 inch, 3 ft)', 'चटाई जाली (2x2 इंच, 3 फीट)'),
        ('Building Materials', 'Chatai Jali (2x2 inch, 4 ft)', 'चटाई जाली (2x2 इंच, 4 फीट)'),
        ('Building Materials', 'Chatai Jali (2x2 inch, 5 ft)', 'चटाई जाली (2x2 इंच, 5 फीट)'),
        ('Building Materials', 'Chatai Jali (2x2 inch, 6 ft)', 'चटाई जाली (2x2 इंच, 6 फीट)'),
        ('Building Materials', 'Chatai Jali (4x4 inch, 3 ft)', 'चटाई जाली (4x4 इंच, 3 फीट)'),
        ('Building Materials', 'Chatai Jali (4x4 inch, 4 ft)', 'चटाई जाली (4x4 इंच, 4 फीट)'),
        ('Building Materials', 'Chatai Jali (4x4 inch, 5 ft)', 'चटाई जाली (4x4 इंच, 5 फीट)'),
        ('Building Materials', 'Chatai Jali (4x4 inch, 6 ft)', 'चटाई जाली (4x4 इंच, 6 फीट)'),
        ('Building Materials', 'Machhardani Jali - Fibreglass (3 ft width, 30 m roll)', 'मच्छरदानी जाली - फाइबरग्लास (3 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Fibreglass (4 ft width, 30 m roll)', 'मच्छरदानी जाली - फाइबरग्लास (4 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Fibreglass (5 ft width, 30 m roll)', 'मच्छरदानी जाली - फाइबरग्लास (5 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Fibreglass (6 ft width, 30 m roll)', 'मच्छरदानी जाली - फाइबरग्लास (6 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Aluminium (3 ft width, 30 m roll)', 'मच्छरदानी जाली - एल्यूमिनियम (3 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Aluminium (4 ft width, 30 m roll)', 'मच्छरदानी जाली - एल्यूमिनियम (4 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Aluminium (5 ft width, 30 m roll)', 'मच्छरदानी जाली - एल्यूमिनियम (5 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - Aluminium (6 ft width, 30 m roll)', 'मच्छरदानी जाली - एल्यूमिनियम (6 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - SS 304 (3 ft width, 30 m roll)', 'मच्छरदानी जाली - SS 304 (3 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - SS 304 (4 ft width, 30 m roll)', 'मच्छरदानी जाली - SS 304 (4 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - SS 304 (5 ft width, 30 m roll)', 'मच्छरदानी जाली - SS 304 (5 फीट चौड़ाई)'),
        ('Building Materials', 'Machhardani Jali - SS 304 (6 ft width, 30 m roll)', 'मच्छरदानी जाली - SS 304 (6 फीट चौड़ाई)'),
        ('Building Materials', 'Waterproofing Chemical', 'वाटरप्रूफिंग केमिकल'),
        ('Building Materials', 'Shuttering Clamp', 'शटरिंग क्लैंप'),
        ('Building Materials', 'Bans (8 ft)', 'बांस (8 फीट)'),
        ('Building Materials', 'Bans (12 ft)', 'बांस (12 फीट)'),
        ('Building Materials', 'Naariyal Rassi (6mm)', 'नारियल रस्सी (6मिमी)'),
        ('Building Materials', 'Naariyal Rassi (10mm)', 'नारियल रस्सी (10मिमी)'),
        ('Building Materials', 'Nylon Rassi (6mm)', 'नायलॉन रस्सी (6मिमी)'),
        ('Building Materials', 'Nylon Rassi (10mm)', 'नायलॉन रस्सी (10मिमी)'),
        ('Building Materials', 'Jute Rassi (8mm)', 'Jute रस्सी (8मिमी)'),
        ('Building Materials', 'Bora', 'Bora'),
        ('Building Materials', 'GI Taar (6 SWG / 4.88 mm)', 'GI तार (6 SWG / 4.88 मिमी)'),
        ('Building Materials', 'GI Taar (8 SWG / 4.06 mm)', 'GI तार (8 SWG / 4.06 मिमी)'),
        ('Building Materials', 'GI Taar (10 SWG / 3.25 mm)', 'GI तार (10 SWG / 3.25 मिमी)'),
        ('Building Materials', 'GI Taar (12 SWG / 2.64 mm)', 'GI तार (12 SWG / 2.64 मिमी)'),
        ('Building Materials', 'GI Taar (14 SWG / 2.03 mm)', 'GI तार (14 SWG / 2.03 मिमी)'),
        ('Building Materials', 'Taar (16 SWG / 1.63 mm)', 'तार (16 SWG / 1.63 मिमी)'),
        ('Building Materials', 'Taar (18 SWG / 1.22 mm)', 'तार (18 SWG / 1.22 मिमी)'),
        ('Building Materials', 'Taar (20 SWG / 0.91 mm)', 'तार (20 SWG / 0.91 मिमी)'),
        ('Building Materials', 'Taar (22 SWG / 0.71 mm)', 'तार (22 SWG / 0.71 मिमी)'),
        ('Building Materials', 'Putty (1 Kg)', 'पुट्टी (1 किलो)'),
        ('Building Materials', 'Putty (2 Kg)', 'पुट्टी (2 किलो)'),
        ('Building Materials', 'Putty (5 Kg)', 'पुट्टी (5 किलो)'),
        ('Building Materials', 'Putty (10 Kg)', 'पुट्टी (10 किलो)'),
        ('Building Materials', 'Putty (25 Kg)', 'पुट्टी (25 किलो)'),
        ('Building Materials', 'Putty (50 Kg)', 'पुट्टी (50 किलो)'),
        ('Hand Tools', 'Hathauri (Claw, 100 g)', 'हथौड़ी (Claw, 100 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 200 g)', 'हथौड़ी (Claw, 200 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 250 g)', 'हथौड़ी (Claw, 250 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 300 g)', 'हथौड़ी (Claw, 300 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 500 g)', 'हथौड़ी (Claw, 500 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 750 g)', 'हथौड़ी (Claw, 750 ग्राम)'),
        ('Hand Tools', 'Hathauri (Claw, 1 Kg)', 'हथौड़ी (Claw, 1 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (2 Kg)', 'बड़ा हथौड़ा / घन (2 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (3 Kg)', 'बड़ा हथौड़ा / घन (3 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (4 Kg)', 'बड़ा हथौड़ा / घन (4 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (5 Kg)', 'बड़ा हथौड़ा / घन (5 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (6 Kg)', 'बड़ा हथौड़ा / घन (6 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (8 Kg)', 'बड़ा हथौड़ा / घन (8 किलो)'),
        ('Hand Tools', 'Bada Hathaura / Ghan (10 Kg)', 'बड़ा हथौड़ा / घन (10 किलो)'),
        ('Hand Tools', 'Plass', 'प्लास'),
        ('Hand Tools', 'Noki Plass', 'नोकी प्लास'),
        ('Hand Tools', 'Silai Paana', 'सिलाई पाना'),
        ('Hand Tools', 'Dafal Paana Set (8-9mm)', 'डफल पाना सेट (8-9मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (10-11mm)', 'डफल पाना सेट (10-11मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (12-13mm)', 'डफल पाना सेट (12-13मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (14-15mm)', 'डफल पाना सेट (14-15मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (16-17mm)', 'डफल पाना सेट (16-17मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (18-19mm)', 'डफल पाना सेट (18-19मिमी)'),
        ('Hand Tools', 'Dafal Paana Set (20-22mm)', 'डफल पाना सेट (20-22मिमी)'),
        ('Hand Tools', 'Ring Paana Set (8-9mm)', 'रिंग पाना सेट (8-9मिमी)'),
        ('Hand Tools', 'Ring Paana Set (10-11mm)', 'रिंग पाना सेट (10-11मिमी)'),
        ('Hand Tools', 'Ring Paana Set (12-13mm)', 'रिंग पाना सेट (12-13मिमी)'),
        ('Hand Tools', 'Ring Paana Set (14-15mm)', 'रिंग पाना सेट (14-15मिमी)'),
        ('Hand Tools', 'Ring Paana Set (16-17mm)', 'रिंग पाना सेट (16-17मिमी)'),
        ('Hand Tools', 'Ring Paana Set (18-19mm)', 'रिंग पाना सेट (18-19मिमी)'),
        ('Hand Tools', 'Ring Paana Set (20-22mm)', 'रिंग पाना सेट (20-22मिमी)'),
        ('Hand Tools', 'Pipe Wrench', 'पाइप रिंच'),
        ('Hand Tools', 'Pechkas (Chapa)', 'पेचकस (Chapa)'),
        ('Hand Tools', 'Pechkas (Star)', 'पेचकस (Star)'),
        ('Hand Tools', 'Tester', 'टेस्टर'),
        ('Hand Tools', 'Chheni (6 inch)', 'छेनी (6 इंच)'),
        ('Hand Tools', 'Chheni (8 inch)', 'छेनी (8 इंच)'),
        ('Hand Tools', 'Chheni (10 inch)', 'छेनी (10 इंच)'),
        ('Hand Tools', 'Chheni (12 inch)', 'छेनी (12 इंच)'),
        ('Hand Tools', 'Loha Aari Frame', 'लोहा आरी फ्रेम'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10 inch, 18 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10 इंच, 18 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10 inch, 24 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10 इंच, 24 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (10 inch, 32 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (10 इंच, 32 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12 inch, 18 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12 इंच, 18 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12 inch, 24 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12 इंच, 24 TPI)'),
        ('Hand Tools', 'Hacksaw Blade / Aari Patti (12 inch, 32 TPI)', 'हैकसॉ ब्लेड / आरी पट्टी (12 इंच, 32 TPI)'),
        ('Hand Tools', 'Randa', 'रंदा'),
        ('Hand Tools', 'Randa Patti', 'रंदा पट्टी'),
        ('Hand Tools', 'Bada Feeta', 'बड़ा फीता'),
        ('Hand Tools', 'Level Rular / Water Level', 'लेवल Rular / पानी लेवल'),
        ('Hand Tools', 'Guniya', 'गुनिया'),
        ('Hand Tools', 'Tar Cutter', 'तार कटर'),
        ('Hand Tools', 'Chadar Katne Wali Kainchi', 'चादर काटने वाली Kainchi'),
        ('Hand Tools', 'Allen Key Set', 'Allen की सेट'),
        ('Hand Tools', 'Reti (Flat, 6 inch)', 'रेती (चपटी, 6 इंच)'),
        ('Hand Tools', 'Reti (Flat, 8 inch)', 'रेती (चपटी, 8 इंच)'),
        ('Hand Tools', 'Reti (Flat, 10 inch)', 'रेती (चपटी, 10 इंच)'),
        ('Hand Tools', 'Reti (Flat, 12 inch)', 'रेती (चपटी, 12 इंच)'),
        ('Hand Tools', 'Reti (Flat, 14 inch)', 'रेती (चपटी, 14 इंच)'),
        ('Hand Tools', 'Reti (Round, 6 inch)', 'रेती (गोल, 6 इंच)'),
        ('Hand Tools', 'Reti (Round, 8 inch)', 'रेती (गोल, 8 इंच)'),
        ('Hand Tools', 'Reti (Round, 10 inch)', 'रेती (गोल, 10 इंच)'),
        ('Hand Tools', 'Reti (Round, 12 inch)', 'रेती (गोल, 12 इंच)'),
        ('Hand Tools', 'Reti (Round, 14 inch)', 'रेती (गोल, 14 इंच)'),
        ('Hand Tools', 'Reti (Half-Round, 6 inch)', 'रेती (अर्ध-गोल, 6 इंच)'),
        ('Hand Tools', 'Reti (Half-Round, 8 inch)', 'रेती (अर्ध-गोल, 8 इंच)'),
        ('Hand Tools', 'Reti (Half-Round, 10 inch)', 'रेती (अर्ध-गोल, 10 इंच)'),
        ('Hand Tools', 'Reti (Half-Round, 12 inch)', 'रेती (अर्ध-गोल, 12 इंच)'),
        ('Hand Tools', 'Reti (Half-Round, 14 inch)', 'रेती (अर्ध-गोल, 14 इंच)'),
        ('Hand Tools', 'Reti (Square, 6 inch)', 'रेती (चौकोर, 6 इंच)'),
        ('Hand Tools', 'Reti (Square, 8 inch)', 'रेती (चौकोर, 8 इंच)'),
        ('Hand Tools', 'Reti (Square, 10 inch)', 'रेती (चौकोर, 10 इंच)'),
        ('Hand Tools', 'Reti (Square, 12 inch)', 'रेती (चौकोर, 12 इंच)'),
        ('Hand Tools', 'Reti (Triangular, 6 inch)', 'रेती (तिकोनी, 6 इंच)'),
        ('Hand Tools', 'Reti (Triangular, 8 inch)', 'रेती (तिकोनी, 8 इंच)'),
        ('Hand Tools', 'Reti (Triangular, 10 inch)', 'रेती (तिकोनी, 10 इंच)'),
        ('Hand Tools', 'Reti (Triangular, 12 inch)', 'रेती (तिकोनी, 12 इंच)'),
        ('Hand Tools', 'Sariya Cutter / Bolt Cutter', 'सरिया कटर / बोल्ट कटर'),
        ('Hand Tools', 'Punch', 'पंच'),
        ('Hand Tools', 'Sabal / Khananti', 'सब्बल / खनन्ती'),
        ('Hand Tools', 'Badhai Cheer Aari (18 inch)', 'बढ़ई Cheer आरी (18 इंच)'),
        ('Hand Tools', 'Tenon Aari (10 inch)', 'Tenon आरी (10 इंच)'),
        ('Hand Tools', 'Basula/Chheni Set (6mm-25mm)', 'बसूला/छेनी सेट (6मिमी-25मिमी)'),
        ('Hand Tools', 'Basula/Chheni (6 mm / 0.25 inch)', 'बसूला/छेनी (6 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (10 mm / 0.375 inch)', 'बसूला/छेनी (10 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (12 mm / 0.5 inch)', 'बसूला/छेनी (12 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (19 mm / 0.75 inch)', 'बसूला/छेनी (19 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (25 mm / 1 inch)', 'बसूला/छेनी (25 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (32 mm / 1.25 inch)', 'बसूला/छेनी (32 मिमी)'),
        ('Hand Tools', 'Basula/Chheni (38 mm / 1.5 inch)', 'बसूला/छेनी (38 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (6 mm)', 'मोर्टिस छेनी (6 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (10 mm)', 'मोर्टिस छेनी (10 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (12 mm)', 'मोर्टिस छेनी (12 मिमी)'),
        ('Hand Tools', 'Mortise Chheni (16 mm)', 'मोर्टिस छेनी (16 मिमी)'),
        ('Hand Tools', 'Lakdi ka Mogra', 'Lakdi का मोगरा'),
        ('Hand Tools', 'Randa (No. 4)', 'रंदा (नंबर 4)'),
        ('Hand Tools', 'Jack Randa (No. 5)', 'Jack रंदा (नंबर 5)'),
        ('Hand Tools', 'Randa Patti', 'रंदा पट्टी'),
        ('Hand Tools', 'Marking Gauge', 'Marking Gauge'),
        ('Hand Tools', 'Soot Dhaga Reel', 'Soot धागा Reel'),
        ('Hand Tools', 'Badhai Pencil', 'बढ़ई Pencil'),
        ('Hand Tools', 'Bevel', 'Bevel'),
        ('Hand Tools', 'Barma (6mm-25mm bit)', 'Barma (6मिमी-25मिमी bit)'),
        ('Hand Tools', 'Sooja', 'सूजा'),
        ('Hand Tools', 'C-Clamp (2 inch)', 'C-क्लैंप (2 इंच)'),
        ('Hand Tools', 'C-Clamp (4 inch)', 'C-क्लैंप (4 इंच)'),
        ('Hand Tools', 'C-Clamp (6 inch)', 'C-क्लैंप (6 इंच)'),
        ('Hand Tools', 'G-Clamp (4 inch)', 'G-क्लैंप (4 इंच)'),
        ('Hand Tools', 'G-Clamp (6 inch)', 'G-क्लैंप (6 इंच)'),
        ('Hand Tools', 'Badhai Shikanja (4 inch)', 'बढ़ई शिकंजा (4 इंच)'),
        ('Hand Tools', 'Badhai Shikanja (6 inch)', 'बढ़ई शिकंजा (6 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 8 inch)', 'खुरदरी रेती - लकड़ी (चपटी, 8 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 10 inch)', 'खुरदरी रेती - लकड़ी (चपटी, 10 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Flat, 12 inch)', 'खुरदरी रेती - लकड़ी (चपटी, 12 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 8 inch)', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 8 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 10 inch)', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 10 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Half-Round, 12 inch)', 'खुरदरी रेती - लकड़ी (अर्ध-गोल, 12 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 8 inch)', 'खुरदरी रेती - लकड़ी (गोल, 8 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 10 inch)', 'खुरदरी रेती - लकड़ी (गोल, 10 इंच)'),
        ('Hand Tools', 'Khurduri Reti - Lakdi (Round, 12 inch)', 'खुरदरी रेती - लकड़ी (गोल, 12 इंच)'),
        ('Hand Tools', 'Keel Punch', 'Keel पंच'),
        ('Hand Tools', 'Polish Brush (1 inch)', 'पॉलिश ब्रश (1 इंच)'),
        ('Hand Tools', 'Polish Brush (2 inch)', 'पॉलिश ब्रश (2 इंच)'),
        ('Hand Tools', 'Karya Mez', 'कार्य मेज़'),
        ('Hand Tools', 'Taar Wala Brush', 'तार वाला ब्रश'),
        ('Hand Tools', 'Toilet Brush', 'टॉयलेट ब्रश'),
        ('Hand Tools', 'Taarkol Brush (3 inch)', 'Taarkol ब्रश (3 इंच)'),
        ('Hand Tools', 'Ragadne Wala Brush', 'रगड़ने वाला ब्रश'),
        ('Hand Tools', 'Aari (8 inch)', 'आरी (8 इंच)'),
        ('Hand Tools', 'Aari (10 inch)', 'आरी (10 इंच)'),
        ('Hand Tools', 'Aari (12 inch)', 'आरी (12 इंच)'),
        ('Hand Tools', 'Aari (14 inch)', 'आरी (14 इंच)'),
        ('Hand Tools', 'Aari (18 inch)', 'आरी (18 इंच)'),
        ('Hand Tools', 'Aari (24 inch)', 'आरी (24 इंच)'),
        ('Hand Tools', 'Saahul (100 g)', 'साहुल (100 ग्राम)'),
        ('Hand Tools', 'Saahul (200 g)', 'साहुल (200 ग्राम)'),
        ('Hand Tools', 'Saahul (250 g)', 'साहुल (250 ग्राम)'),
        ('Hand Tools', 'Saahul (500 g)', 'साहुल (500 ग्राम)'),
        ('Hand Tools', 'Karni (4 inch)', 'करनी (4 इंच)'),
        ('Hand Tools', 'Karni (5 inch)', 'करनी (5 इंच)'),
        ('Hand Tools', 'Karni (6 inch)', 'करनी (6 इंच)'),
        ('Hand Tools', 'Karni (7 inch)', 'करनी (7 इंच)'),
        ('Power Tools', 'Hole Machine / Drill Machine', 'Hole मशीन / ड्रिल मशीन'),
        ('Power Tools', 'Chitai Machine / Demolition Drill', 'Chitai मशीन / Demolition ड्रिल'),
        ('Power Tools', 'Grinder Machine / Glazer', 'Grinder मशीन / Glazer'),
        ('Power Tools', 'Tile Katne Wali Machine', 'टाइल काटने वाली मशीन'),
        ('Power Tools', 'Bijli Randa Machine', 'बिजली रंदा मशीन'),
        ('Power Tools', 'Gol Aari Machine', 'गोल आरी मशीन'),
        ('Power Tools', 'Jigsaw Machine', 'जिगसॉ मशीन'),
        ('Power Tools', 'Battery Drill Machine', 'Battery ड्रिल मशीन'),
        ('Power Tools', 'Dewal Bit (5mm)', 'दीवाल बिट (5मिमी)'),
        ('Power Tools', 'Dewal Bit (6mm)', 'दीवाल बिट (6मिमी)'),
        ('Power Tools', 'Dewal Bit (8mm)', 'दीवाल बिट (8मिमी)'),
        ('Power Tools', 'Dewal Bit (10mm)', 'दीवाल बिट (10मिमी)'),
        ('Power Tools', 'Dewal Bit (12mm)', 'दीवाल बिट (12मिमी)'),
        ('Power Tools', 'Dewal Bit (14mm)', 'दीवाल बिट (14मिमी)'),
        ('Power Tools', 'Dewal Bit (16mm)', 'दीवाल बिट (16मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (5mm)', 'लोहा/लकड़ी बिट (5मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (6mm)', 'लोहा/लकड़ी बिट (6मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (8mm)', 'लोहा/लकड़ी बिट (8मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (10mm)', 'लोहा/लकड़ी बिट (10मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (12mm)', 'लोहा/लकड़ी बिट (12मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (14mm)', 'लोहा/लकड़ी बिट (14मिमी)'),
        ('Power Tools', 'Loha/Lakri Bit (16mm)', 'लोहा/लकड़ी बिट (16मिमी)'),
        ('Power Tools', 'Marbal Patti / Diamond Blade', 'Marbal पट्टी / डायमंड ब्लेड'),
        ('Power Tools', 'Grinding Pathar', 'ग्राइंडिंग Pathar'),
        ('Power Tools', 'Loha Kata Patti', 'लोहा कटा पट्टी'),
        ('Power Tools', 'Polishing Disc', 'Polishing Disc'),
        ('Power Tools', 'Machine Carbon', 'मशीन Carbon'),
        ('Power Tools', 'Drill Chabi & Chuck', 'ड्रिल चाबी & चक'),
        ('Plumbing', 'CPVC (0.5 inch SDR 11)', 'सीपीवीसी (0.5 इंच SDR 11)'),
        ('Plumbing', 'CPVC (0.75 inch SDR 11)', 'सीपीवीसी (0.75 इंच SDR 11)'),
        ('Plumbing', 'CPVC (1 inch SDR 11)', 'सीपीवीसी (1 इंच SDR 11)'),
        ('Plumbing', 'CPVC (1.25 inch SDR 11)', 'सीपीवीसी (1.25 इंच SDR 11)'),
        ('Plumbing', 'CPVC (1.5 inch SDR 11)', 'सीपीवीसी (1.5 इंच SDR 11)'),
        ('Plumbing', 'CPVC (2 inch SDR 11)', 'सीपीवीसी (2 इंच SDR 11)'),
        ('Plumbing', 'UPVC Pipe (0.5 inch, 10 ft)', 'UPVC पाइप (0.5 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (0.75 inch, 10 ft)', 'UPVC पाइप (0.75 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1 inch, 10 ft)', 'UPVC पाइप (1 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1.25 inch, 10 ft)', 'UPVC पाइप (1.25 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (1.5 inch, 10 ft)', 'UPVC पाइप (1.5 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (2 inch, 10 ft)', 'UPVC पाइप (2 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (3 inch, 10 ft)', 'UPVC पाइप (3 इंच, 10 फीट)'),
        ('Plumbing', 'UPVC Pipe (4 inch, 10 ft)', 'UPVC पाइप (4 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1 inch, 10 ft)', 'खेती/नाला पाइप (1 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1.25 inch, 10 ft)', 'खेती/नाला पाइप (1.25 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (1.5 inch, 10 ft)', 'खेती/नाला पाइप (1.5 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (2 inch, 10 ft)', 'खेती/नाला पाइप (2 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (3 inch, 10 ft)', 'खेती/नाला पाइप (3 इंच, 10 फीट)'),
        ('Plumbing', 'Kheti/Nala Pipe (4 inch, 10 ft)', 'खेती/नाला पाइप (4 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (0.5 inch, 10 ft)', 'लोहा पाइप (0.5 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (0.75 inch, 10 ft)', 'लोहा पाइप (0.75 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1 inch, 10 ft)', 'लोहा पाइप (1 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1.25 inch, 10 ft)', 'लोहा पाइप (1.25 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (1.5 inch, 10 ft)', 'लोहा पाइप (1.5 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (2 inch, 10 ft)', 'लोहा पाइप (2 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (3 inch, 10 ft)', 'लोहा पाइप (3 इंच, 10 फीट)'),
        ('Plumbing', 'Loha Pipe (4 inch, 10 ft)', 'लोहा पाइप (4 इंच, 10 फीट)'),
        ('Plumbing', 'CPVC Elbow (0.5 inch)', 'सीपीवीसी एल्बो (0.5 इंच)'),
        ('Plumbing', 'CPVC Elbow (0.75 inch)', 'सीपीवीसी एल्बो (0.75 इंच)'),
        ('Plumbing', 'CPVC Elbow (1 inch)', 'सीपीवीसी एल्बो (1 इंच)'),
        ('Plumbing', 'CPVC Elbow (1.25 inch)', 'सीपीवीसी एल्बो (1.25 इंच)'),
        ('Plumbing', 'CPVC Elbow (1.5 inch)', 'सीपीवीसी एल्बो (1.5 इंच)'),
        ('Plumbing', 'CPVC Elbow (2 inch)', 'सीपीवीसी एल्बो (2 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (0.5 inch)', 'सीपीवीसी टी / T-Joint (0.5 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (0.75 inch)', 'सीपीवीसी टी / T-Joint (0.75 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (1 inch)', 'सीपीवीसी टी / T-Joint (1 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (1.25 inch)', 'सीपीवीसी टी / T-Joint (1.25 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (1.5 inch)', 'सीपीवीसी टी / T-Joint (1.5 इंच)'),
        ('Plumbing', 'CPVC Tee / T-Joint (2 inch)', 'सीपीवीसी टी / T-Joint (2 इंच)'),
        ('Plumbing', 'CPVC Socket (0.5 inch)', 'सीपीवीसी सॉकेट (0.5 इंच)'),
        ('Plumbing', 'CPVC Socket (0.75 inch)', 'सीपीवीसी सॉकेट (0.75 इंच)'),
        ('Plumbing', 'CPVC Socket (1 inch)', 'सीपीवीसी सॉकेट (1 इंच)'),
        ('Plumbing', 'CPVC Socket (1.25 inch)', 'सीपीवीसी सॉकेट (1.25 इंच)'),
        ('Plumbing', 'CPVC Socket (1.5 inch)', 'सीपीवीसी सॉकेट (1.5 इंच)'),
        ('Plumbing', 'CPVC Socket (2 inch)', 'सीपीवीसी सॉकेट (2 इंच)'),
        ('Plumbing', 'CPVC Union', 'सीपीवीसी Union'),
        ('Plumbing', 'Reducer / Ghatane Wala', 'Reducer / Ghatane वाला'),
        ('Plumbing', 'Ball Valve / Chabi / Handle', 'बॉल वाल्व / चाबी / हैंडल'),
        ('Plumbing', 'Brass MTA', 'पीतल MTA'),
        ('Plumbing', 'Brass FTA', 'पीतल FTA'),
        ('Plumbing', 'Brass Elbow (Nal Point)', 'पीतल एल्बो (Nal Point)'),
        ('Plumbing', 'CPVC Solution / Gum', 'सीपीवीसी सोल्यूशन / गोंद'),
        ('Plumbing', 'UPVC Solution', 'यूपीवीसी सोल्यूशन'),
        ('Plumbing', 'Slipping Grease / Lubricant', 'Slipping ग्रीस / Lubricant'),
        ('Plumbing', 'Teflon Tape (12 mm x 5 m)', 'Teflon टेप (12 मिमी x 5 मी)'),
        ('Plumbing', 'Teflon Tape (12 mm x 10 m)', 'Teflon टेप (12 मिमी x 10 मी)'),
        ('Plumbing', 'Teflon Tape (19 mm x 10 m)', 'Teflon टेप (19 मिमी x 10 मी)'),
        ('Plumbing', 'Teflon Tape (25 mm x 10 m)', 'Teflon टेप (25 मिमी x 10 मी)'),
        ('Plumbing', 'Sutli / Dhaga', 'सुतली / धागा'),
        ('Plumbing', 'M-Seal (30 g)', 'M-Seal (30 ग्राम)'),
        ('Plumbing', 'M-Seal (50 g)', 'M-Seal (50 ग्राम)'),
        ('Plumbing', 'M-Seal (100 g)', 'M-Seal (100 ग्राम)'),
        ('Plumbing', 'M-Seal (200 g)', 'M-Seal (200 ग्राम)'),
        ('Plumbing', 'M-Seal (500 g)', 'M-Seal (500 ग्राम)'),
        ('Plumbing', 'M-Seal (1 Kg)', 'M-Seal (1 किलो)'),
        ('Plumbing', 'Nal / Totii', 'नल / Totii'),
        ('Plumbing', 'Basin Nal', 'बेसिन नल'),
        ('Plumbing', 'Angle Valve', 'एंगल वाल्व'),
        ('Plumbing', 'Concealed Wall Valve', 'छुपा हुआ दीवाल वाल्व'),
        ('Plumbing', 'Spray / Faucet', 'स्प्रे / Faucet'),
        ('Plumbing', 'Jharana / Shower', 'Jharana / Shower'),
        ('Plumbing', 'Connection Pipe / Connection Tar', 'कनेक्शन पाइप / कनेक्शन तार'),
        ('Plumbing', 'Basin / Sink Pipe', 'बेसिन / सिंक पाइप'),
        ('Plumbing', 'Jali Trap / Bottle Trap', 'जाली ट्रैप / Bottle ट्रैप'),
        ('Plumbing', 'Floor Jali (4x4 inch)', 'Floor जाली (4x4 इंच)'),
        ('Plumbing', 'Floor Jali (5x5 inch)', 'Floor जाली (5x5 इंच)'),
        ('Plumbing', 'Floor Jali (6x6 inch)', 'Floor जाली (6x6 इंच)'),
        ('Plumbing', 'Steel Floor Jali (4x4 inch)', 'स्टील Floor जाली (4x4 इंच)'),
        ('Plumbing', 'Steel Floor Jali (5x5 inch)', 'स्टील Floor जाली (5x5 इंच)'),
        ('Plumbing', 'Steel Floor Jali (6x6 inch)', 'स्टील Floor जाली (6x6 इंच)'),
        ('Plumbing', 'Nahani Trap', 'Nahani ट्रैप'),
        ('Plumbing', 'Desi Latrine Seat', 'Desi Latrine सीट'),
        ('Plumbing', 'Angreji Seat / Commode', 'Angreji सीट / Commode'),
        ('Plumbing', 'Basin', 'बेसिन'),
        ('Plumbing', 'Steel Sink', 'स्टील सिंक'),
        ('Plumbing', 'Flush Tank', 'फ्लश Tank'),
        ('Plumbing', 'Flush Kit / Syphon Set', 'फ्लश किट / Syphon सेट'),
        ('Plumbing', 'Seat Dhakkan', 'सीट Dhakkan'),
        ('Plumbing', 'Pani Tanki', 'पानी टंकी'),
        ('Plumbing', 'Tanki Nipple (0.5 inch)', 'टंकी निप्पल (0.5 इंच)'),
        ('Plumbing', 'Tanki Nepul (0.75 inch)', 'टंकी नेपुल (0.75 इंच)'),
        ('Plumbing', 'Tanki Nepul (1 inch)', 'टंकी नेपुल (1 इंच)'),
        ('Plumbing', 'Tanki Nepul (1.5 inch)', 'टंकी नेपुल (1.5 इंच)'),
        ('Plumbing', 'Tanki Nepul (2 inch)', 'टंकी नेपुल (2 इंच)'),
        ('Plumbing', 'Auto-Cut Valve / Ball Cock', 'Auto-Cut वाल्व / बॉल Cock'),
        ('Plumbing', 'Delivery Pipe / Delivery Hose', 'डिलीवरी पाइप / डिलीवरी Hose'),
        ('Plumbing', 'Water Pipe / Level Pipe', 'पानी पाइप / लेवल पाइप'),
        ('Plumbing', 'Pipe Clamp / Patti', 'पाइप क्लैंप / पट्टी'),
        ('Plumbing', 'PVC Saddle / Clamp', 'पीवीसी Saddle / क्लैंप'),
        ('Plumbing', 'UPVC Elbow (0.5 inch)', 'यूपीवीसी एल्बो (0.5 इंच)'),
        ('Plumbing', 'UPVC Elbow (0.75 inch)', 'यूपीवीसी एल्बो (0.75 इंच)'),
        ('Plumbing', 'UPVC Elbow (1 inch)', 'यूपीवीसी एल्बो (1 इंच)'),
        ('Plumbing', 'UPVC Elbow (1.5 inch)', 'यूपीवीसी एल्बो (1.5 इंच)'),
        ('Plumbing', 'UPVC Elbow (2 inch)', 'यूपीवीसी एल्बो (2 इंच)'),
        ('Plumbing', 'UPVC Elbow (3 inch)', 'यूपीवीसी एल्बो (3 इंच)'),
        ('Plumbing', 'UPVC Elbow (4 inch)', 'यूपीवीसी एल्बो (4 इंच)'),
        ('Plumbing', 'UPVC Tee (0.5 inch)', 'यूपीवीसी टी (0.5 इंच)'),
        ('Plumbing', 'UPVC Tee (0.75 inch)', 'यूपीवीसी टी (0.75 इंच)'),
        ('Plumbing', 'UPVC Tee (1 inch)', 'यूपीवीसी टी (1 इंच)'),
        ('Plumbing', 'UPVC Tee (1.5 inch)', 'यूपीवीसी टी (1.5 इंच)'),
        ('Plumbing', 'UPVC Tee (2 inch)', 'यूपीवीसी टी (2 इंच)'),
        ('Plumbing', 'UPVC Tee (3 inch)', 'यूपीवीसी टी (3 इंच)'),
        ('Plumbing', 'UPVC Tee (4 inch)', 'यूपीवीसी टी (4 इंच)'),
        ('Plumbing', 'UPVC Socket (0.5 inch)', 'यूपीवीसी सॉकेट (0.5 इंच)'),
        ('Plumbing', 'UPVC Socket (0.75 inch)', 'यूपीवीसी सॉकेट (0.75 इंच)'),
        ('Plumbing', 'UPVC Socket (1 inch)', 'यूपीवीसी सॉकेट (1 इंच)'),
        ('Plumbing', 'UPVC Socket (1.5 inch)', 'यूपीवीसी सॉकेट (1.5 इंच)'),
        ('Plumbing', 'UPVC Socket (2 inch)', 'यूपीवीसी सॉकेट (2 इंच)'),
        ('Plumbing', 'UPVC Socket (3 inch)', 'यूपीवीसी सॉकेट (3 इंच)'),
        ('Plumbing', 'UPVC Socket (4 inch)', 'यूपीवीसी सॉकेट (4 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (0.5 inch)', 'पीवीसी नाला/एग्री एल्बो (0.5 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (0.75 inch)', 'पीवीसी नाला/एग्री एल्बो (0.75 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (1 inch)', 'पीवीसी नाला/एग्री एल्बो (1 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (1.5 inch)', 'पीवीसी नाला/एग्री एल्बो (1.5 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (2 inch)', 'पीवीसी नाला/एग्री एल्बो (2 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (3 inch)', 'पीवीसी नाला/एग्री एल्बो (3 इंच)'),
        ('Plumbing', 'PVC Nala/Agri Elbow (4 inch)', 'पीवीसी नाला/एग्री एल्बो (4 इंच)'),
        ('Plumbing', 'PVC Agri Tee (0.5 inch)', 'पीवीसी एग्री टी (0.5 इंच)'),
        ('Plumbing', 'PVC Agri Tee (0.75 inch)', 'पीवीसी एग्री टी (0.75 इंच)'),
        ('Plumbing', 'PVC Agri Tee (1 inch)', 'पीवीसी एग्री टी (1 इंच)'),
        ('Plumbing', 'PVC Agri Tee (1.5 inch)', 'पीवीसी एग्री टी (1.5 इंच)'),
        ('Plumbing', 'PVC Agri Tee (2 inch)', 'पीवीसी एग्री टी (2 इंच)'),
        ('Plumbing', 'PVC Agri Tee (3 inch)', 'पीवीसी एग्री टी (3 इंच)'),
        ('Plumbing', 'PVC Agri Tee (4 inch)', 'पीवीसी एग्री टी (4 इंच)'),
        ('Plumbing', 'SWR Coupler (0.5 inch)', 'एसडब्ल्यूआर कपलर (0.5 इंच)'),
        ('Plumbing', 'SWR Coupler (0.75 inch)', 'एसडब्ल्यूआर कपलर (0.75 इंच)'),
        ('Plumbing', 'SWR Coupler (1 inch)', 'एसडब्ल्यूआर कपलर (1 इंच)'),
        ('Plumbing', 'SWR Coupler (1.5 inch)', 'एसडब्ल्यूआर कपलर (1.5 इंच)'),
        ('Plumbing', 'SWR Coupler (2 inch)', 'एसडब्ल्यूआर कपलर (2 इंच)'),
        ('Plumbing', 'SWR Coupler (3 inch)', 'एसडब्ल्यूआर कपलर (3 इंच)'),
        ('Plumbing', 'SWR Coupler (4 inch)', 'एसडब्ल्यूआर कपलर (4 इंच)'),
        ('Plumbing', 'SWR Door Kona (0.5 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (0.5 इंच)'),
        ('Plumbing', 'SWR Door Kona (0.75 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (0.75 इंच)'),
        ('Plumbing', 'SWR Door Kona (1 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (1 इंच)'),
        ('Plumbing', 'SWR Door Kona (1.5 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (1.5 इंच)'),
        ('Plumbing', 'SWR Door Kona (2 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (2 इंच)'),
        ('Plumbing', 'SWR Door Kona (3 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (3 इंच)'),
        ('Plumbing', 'SWR Door Kona (4 inch)', 'एसडब्ल्यूआर दरवाज़ा कोना (4 इंच)'),
        ('Plumbing', 'SWR Y-Joint (0.5 inch)', 'एसडब्ल्यूआर Y-Joint (0.5 इंच)'),
        ('Plumbing', 'SWR Y-Joint (0.75 inch)', 'एसडब्ल्यूआर Y-Joint (0.75 इंच)'),
        ('Plumbing', 'SWR Y-Joint (1 inch)', 'एसडब्ल्यूआर Y-Joint (1 इंच)'),
        ('Plumbing', 'SWR Y-Joint (1.5 inch)', 'एसडब्ल्यूआर Y-Joint (1.5 इंच)'),
        ('Plumbing', 'SWR Y-Joint (2 inch)', 'एसडब्ल्यूआर Y-Joint (2 इंच)'),
        ('Plumbing', 'SWR Y-Joint (3 inch)', 'एसडब्ल्यूआर Y-Joint (3 इंच)'),
        ('Plumbing', 'SWR Y-Joint (4 inch)', 'एसडब्ल्यूआर Y-Joint (4 इंच)'),
        ('Plumbing', 'Loha Elbow (0.5 inch)', 'लोहा एल्बो (0.5 इंच)'),
        ('Plumbing', 'Loha Elbow (0.75 inch)', 'लोहा एल्बो (0.75 इंच)'),
        ('Plumbing', 'Loha Elbow (1 inch)', 'लोहा एल्बो (1 इंच)'),
        ('Plumbing', 'Loha Elbow (1.5 inch)', 'लोहा एल्बो (1.5 इंच)'),
        ('Plumbing', 'Loha Elbow (2 inch)', 'लोहा एल्बो (2 इंच)'),
        ('Plumbing', 'Loha Elbow (3 inch)', 'लोहा एल्बो (3 इंच)'),
        ('Plumbing', 'Loha Elbow (4 inch)', 'लोहा एल्बो (4 इंच)'),
        ('Plumbing', 'Loha Tee (0.5 inch)', 'लोहा टी (0.5 इंच)'),
        ('Plumbing', 'Loha Tee (0.75 inch)', 'लोहा टी (0.75 इंच)'),
        ('Plumbing', 'Loha Tee (1 inch)', 'लोहा टी (1 इंच)'),
        ('Plumbing', 'Loha Tee (1.5 inch)', 'लोहा टी (1.5 इंच)'),
        ('Plumbing', 'Loha Tee (2 inch)', 'लोहा टी (2 इंच)'),
        ('Plumbing', 'Loha Tee (3 inch)', 'लोहा टी (3 इंच)'),
        ('Plumbing', 'Loha Tee (4 inch)', 'लोहा टी (4 इंच)'),
        ('Plumbing', 'Loha Socket (0.5 inch)', 'लोहा सॉकेट (0.5 इंच)'),
        ('Plumbing', 'Loha Socket (0.75 inch)', 'लोहा सॉकेट (0.75 इंच)'),
        ('Plumbing', 'Loha Socket (1 inch)', 'लोहा सॉकेट (1 इंच)'),
        ('Plumbing', 'Loha Socket (1.5 inch)', 'लोहा सॉकेट (1.5 इंच)'),
        ('Plumbing', 'Loha Socket (2 inch)', 'लोहा सॉकेट (2 इंच)'),
        ('Plumbing', 'Loha Socket (3 inch)', 'लोहा सॉकेट (3 इंच)'),
        ('Plumbing', 'Loha Socket (4 inch)', 'लोहा सॉकेट (4 इंच)'),
        ('Plumbing', 'Hex Nipple (0.5 inch)', 'हेक्स निप्पल (0.5 इंच)'),
        ('Plumbing', 'Hex Nepul (0.75 inch)', 'हेक्स नेपुल (0.75 इंच)'),
        ('Plumbing', 'Hex Nepul (1 inch)', 'हेक्स नेपुल (1 इंच)'),
        ('Plumbing', 'Hex Nepul (1.5 inch)', 'हेक्स नेपुल (1.5 इंच)'),
        ('Plumbing', 'Hex Nepul (2 inch)', 'हेक्स नेपुल (2 इंच)'),
        ('Plumbing', 'Hex Nepul (3 inch)', 'हेक्स नेपुल (3 इंच)'),
        ('Plumbing', 'Hex Nepul (4 inch)', 'हेक्स नेपुल (4 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 2 inch)', 'निप्पल (0.5 इंच x 2 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 4 inch)', 'निप्पल (0.5 इंच x 4 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 6 inch)', 'निप्पल (0.5 इंच x 6 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 8 inch)', 'निप्पल (0.5 इंच x 8 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 9 inch)', 'निप्पल (0.5 इंच x 9 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 12 inch)', 'निप्पल (0.5 इंच x 12 इंच)'),
        ('Plumbing', 'Nipple (0.5 inch x 10 ft)', 'निप्पल (0.5 इंच x 10 फीट)'),
        ('Plumbing', 'Nepul (0.75 inch x 2 inch)', 'नेपुल (0.75 इंच x 2 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 4 inch)', 'नेपुल (0.75 इंच x 4 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 6 inch)', 'नेपुल (0.75 इंच x 6 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 8 inch)', 'नेपुल (0.75 इंच x 8 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 9 inch)', 'नेपुल (0.75 इंच x 9 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 12 inch)', 'नेपुल (0.75 इंच x 12 इंच)'),
        ('Plumbing', 'Nepul (0.75 inch x 10 ft)', 'नेपुल (0.75 इंच x 10 फीट)'),
        ('Plumbing', 'Nepul (1 inch x 2 inch)', 'नेपुल (1 इंच x 2 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 4 inch)', 'नेपुल (1 इंच x 4 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 6 inch)', 'नेपुल (1 इंच x 6 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 8 inch)', 'नेपुल (1 इंच x 8 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 9 inch)', 'नेपुल (1 इंच x 9 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 12 inch)', 'नेपुल (1 इंच x 12 इंच)'),
        ('Plumbing', 'Nepul (1 inch x 10 ft)', 'नेपुल (1 इंच x 10 फीट)'),
        ('Plumbing', 'Nepul (1.5 inch x 2 inch)', 'नेपुल (1.5 इंच x 2 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 4 inch)', 'नेपुल (1.5 इंच x 4 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 6 inch)', 'नेपुल (1.5 इंच x 6 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 8 inch)', 'नेपुल (1.5 इंच x 8 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 9 inch)', 'नेपुल (1.5 इंच x 9 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 12 inch)', 'नेपुल (1.5 इंच x 12 इंच)'),
        ('Plumbing', 'Nepul (1.5 inch x 10 ft)', 'नेपुल (1.5 इंच x 10 फीट)'),
        ('Plumbing', 'Heavy Brass Nal (0.5 inch)', 'भारी पीतल नल (0.5 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (0.75 inch)', 'भारी पीतल नल (0.75 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (1 inch)', 'भारी पीतल नल (1 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (1.5 inch)', 'भारी पीतल नल (1.5 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (2 inch)', 'भारी पीतल नल (2 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (3 inch)', 'भारी पीतल नल (3 इंच)'),
        ('Plumbing', 'Heavy Brass Nal (4 inch)', 'भारी पीतल नल (4 इंच)'),
        ('Plumbing', 'Brass Stop Valve (0.5 inch)', 'पीतल स्टॉप वाल्व (0.5 इंच)'),
        ('Plumbing', 'Brass Stop Valve (0.75 inch)', 'पीतल स्टॉप वाल्व (0.75 इंच)'),
        ('Plumbing', 'Brass Stop Valve (1 inch)', 'पीतल स्टॉप वाल्व (1 इंच)'),
        ('Plumbing', 'Brass Stop Valve (1.5 inch)', 'पीतल स्टॉप वाल्व (1.5 इंच)'),
        ('Plumbing', 'Brass Stop Valve (2 inch)', 'पीतल स्टॉप वाल्व (2 इंच)'),
        ('Plumbing', 'Brass Stop Valve (3 inch)', 'पीतल स्टॉप वाल्व (3 इंच)'),
        ('Plumbing', 'Brass Stop Valve (4 inch)', 'पीतल स्टॉप वाल्व (4 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (0.5 inch)', 'स्टील फिनिश लंबा नल (0.5 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (0.75 inch)', 'स्टील फिनिश लंबा नल (0.75 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (1 inch)', 'स्टील फिनिश लंबा नल (1 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (1.5 inch)', 'स्टील फिनिश लंबा नल (1.5 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (2 inch)', 'स्टील फिनिश लंबा नल (2 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (3 inch)', 'स्टील फिनिश लंबा नल (3 इंच)'),
        ('Plumbing', 'Steel Finish Lamba Nal (4 inch)', 'स्टील फिनिश लंबा नल (4 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (0.5 inch)', 'बेसिन मिक्सर वाल्व (0.5 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (0.75 inch)', 'बेसिन मिक्सर वाल्व (0.75 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (1 inch)', 'बेसिन मिक्सर वाल्व (1 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (1.5 inch)', 'बेसिन मिक्सर वाल्व (1.5 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (2 inch)', 'बेसिन मिक्सर वाल्व (2 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (3 inch)', 'बेसिन मिक्सर वाल्व (3 इंच)'),
        ('Plumbing', 'Basin Mixer Valve (4 inch)', 'बेसिन मिक्सर वाल्व (4 इंच)'),
        ('Plumbing', 'Wall Mixer Set (0.5 inch)', 'दीवाल मिक्सर सेट (0.5 इंच)'),
        ('Plumbing', 'Wall Mixer Set (0.75 inch)', 'दीवाल मिक्सर सेट (0.75 इंच)'),
        ('Plumbing', 'Wall Mixer Set (1 inch)', 'दीवाल मिक्सर सेट (1 इंच)'),
        ('Plumbing', 'Wall Mixer Set (1.5 inch)', 'दीवाल मिक्सर सेट (1.5 इंच)'),
        ('Plumbing', 'Wall Mixer Set (2 inch)', 'दीवाल मिक्सर सेट (2 इंच)'),
        ('Plumbing', 'Wall Mixer Set (3 inch)', 'दीवाल मिक्सर सेट (3 इंच)'),
        ('Plumbing', 'Wall Mixer Set (4 inch)', 'दीवाल मिक्सर सेट (4 इंच)'),
        ('Door Hardware', 'Tala (Heavy)', 'ताला (Heavy)'),
        ('Door Hardware', 'Dukan Lock / Shutter Tala', 'Dukan लॉक / ताला / Shutter ताला'),
        ('Door Hardware', 'Handle Lock Set', 'हैंडल लॉक / ताला सेट'),
        ('Door Hardware', 'Gol Lock / Bedroom Lock', 'गोल लॉक / ताला / Bedroom लॉक / ताला'),
        ('Door Hardware', 'Draj Lock / Box Lock', 'Draj लॉक / ताला / बॉक्स लॉक / ताला'),
        ('Door Hardware', 'Gate Lock / Rim Lock', 'Gate लॉक / ताला / Rim लॉक / ताला'),
        ('Door Hardware', 'Kabja (2 inch)', 'कब्जा (2 इंच)'),
        ('Door Hardware', 'Kabja (3 inch)', 'कब्जा (3 इंच)'),
        ('Door Hardware', 'Kabja (4 inch)', 'कब्जा (4 इंच)'),
        ('Door Hardware', 'Kabja (5 inch)', 'कब्जा (5 इंच)'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (2 inch)', 'बॉक्स कब्जा / L-Bihari कब्जा (2 इंच)'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (3 inch)', 'बॉक्स कब्जा / L-Bihari कब्जा (3 इंच)'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (4 inch)', 'बॉक्स कब्जा / L-Bihari कब्जा (4 इंच)'),
        ('Door Hardware', 'Box Kabja / L-Bihari Kabja (5 inch)', 'बॉक्स कब्जा / L-Bihari कब्जा (5 इंच)'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (2 inch)', 'लंबा कब्जा / पियानो कब्जा (2 इंच)'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (3 inch)', 'लंबा कब्जा / पियानो कब्जा (3 इंच)'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (4 inch)', 'लंबा कब्जा / पियानो कब्जा (4 इंच)'),
        ('Door Hardware', 'Lamba Kabja / Piano Kabja (5 inch)', 'लंबा कब्जा / पियानो कब्जा (5 इंच)'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (2 inch)', 'पट्टी कब्जा / कमानी कब्जा (2 इंच)'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (3 inch)', 'पट्टी कब्जा / कमानी कब्जा (3 इंच)'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (4 inch)', 'पट्टी कब्जा / कमानी कब्जा (4 इंच)'),
        ('Door Hardware', 'Patti Kabja / Kamani Kabja (5 inch)', 'पट्टी कब्जा / कमानी कब्जा (5 इंच)'),
        ('Door Hardware', 'Chhitkani (3 inch)', 'छिटकनी (3 इंच)'),
        ('Door Hardware', 'Chhitkani (4 inch)', 'छिटकनी (4 इंच)'),
        ('Door Hardware', 'Chhitkani (6 inch)', 'छिटकनी (6 इंच)'),
        ('Door Hardware', 'Chhitkani (8 inch)', 'छिटकनी (8 इंच)'),
        ('Door Hardware', 'Chhitkani (10 inch)', 'छिटकनी (10 इंच)'),
        ('Door Hardware', 'Chhitkani (12 inch)', 'छिटकनी (12 इंच)'),
        ('Door Hardware', 'Kundi / Aldrop', 'Kundi / अलड्राप'),
        ('Door Hardware', 'Haththa / Handle', 'Haththa / हैंडल'),
        ('Door Hardware', 'Magnet Catcher', 'Magnet Catcher'),
        ('Door Hardware', 'Door Stopper', 'दरवाज़ा Stopper'),
        ('Door Hardware', 'Door Closer (40 Kg)', 'दरवाज़ा Closer (40 किलो तक)'),
        ('Door Hardware', 'Door Closer (60 Kg)', 'दरवाज़ा Closer (60 किलो तक)'),
        ('Door Hardware', 'Door Closer (80 Kg)', 'दरवाज़ा Closer (80 किलो तक)'),
        ('Door Hardware', 'Door Closer (100 Kg)', 'दरवाज़ा Closer (100 किलो तक)'),
        ('Door Hardware', 'Channel / Drawer Channel', 'चैनल / Drawer चैनल'),
        ('Door Hardware', 'Hydraulic Pump / Gas Shock', 'Hydraulic पंप / Gas Shock'),
        ('Door Hardware', 'Khirki Hook', 'खिड़की Hook'),
        ('Door Hardware', 'Khirki Handle', 'खिड़की हैंडल'),
        ('Door Hardware', 'Aina Clamp / Glass Clip', 'आईना क्लैंप / Glass Clip'),
        ('Door Hardware', 'Parda Bracket', 'पर्दा ब्रैकेट'),
        ('Door Hardware', 'Parda Chhalla', 'पर्दा Chhalla'),
        ('Door Hardware', 'Heavy Chhitkani', 'भारी छिटकनी'),
        ('Door Hardware', 'Tala (40 mm)', 'ताला (40 मिमी)'),
        ('Door Hardware', 'Tala (50 mm)', 'ताला (50 मिमी)'),
        ('Door Hardware', 'Tala (65 mm)', 'ताला (65 मिमी)'),
        ('Door Hardware', 'Tala (70 mm)', 'ताला (70 मिमी)'),
        ('Door Hardware', 'Tala (75 mm)', 'ताला (75 मिमी)'),
        ('Door Hardware', 'Link Tala (40 mm)', 'लिंक ताला (40 मिमी)'),
        ('Door Hardware', 'Link Tala (50 mm)', 'लिंक ताला (50 मिमी)'),
        ('Door Hardware', 'Link Tala (65 mm)', 'लिंक ताला (65 मिमी)'),
        ('Door Hardware', 'Link Tala (70 mm)', 'लिंक ताला (70 मिमी)'),
        ('Door Hardware', 'Link Tala (75 mm)', 'लिंक ताला (75 मिमी)'),
        ('Door Hardware', 'Konark Tala (40 mm)', 'कोणार्क ताला (40 मिमी)'),
        ('Door Hardware', 'Konark Tala (50 mm)', 'कोणार्क ताला (50 मिमी)'),
        ('Door Hardware', 'Konark Tala (65 mm)', 'कोणार्क ताला (65 मिमी)'),
        ('Door Hardware', 'Konark Tala (70 mm)', 'कोणार्क ताला (70 मिमी)'),
        ('Door Hardware', 'Konark Tala (75 mm)', 'कोणार्क ताला (75 मिमी)'),
        ('Door Hardware', 'Godrej Navtal Tala', 'गोदरेज नवताल ताला'),
        ('Door Hardware', 'Local Tala', 'लोकल ताला'),
        ('Door Hardware', 'Aldrop (4 inch)', 'अलड्राप (4 इंच)'),
        ('Door Hardware', 'Aldrop (6 inch)', 'अलड्राप (6 इंच)'),
        ('Door Hardware', 'Aldrop (8 inch)', 'अलड्राप (8 इंच)'),
        ('Door Hardware', 'Aldrop (10 inch)', 'अलड्राप (10 इंच)'),
        ('Door Hardware', 'Aldrop (12 inch)', 'अलड्राप (12 इंच)'),
        ('Door Hardware', 'Khirki Handle (2 inch)', 'खिड़की हैंडल (2 इंच)'),
        ('Door Hardware', 'Khirki Handle (3 inch)', 'खिड़की हैंडल (3 इंच)'),
        ('Door Hardware', 'Khirki Handle (4 inch)', 'खिड़की हैंडल (4 इंच)'),
        ('Door Hardware', 'Khirki Handle (6 inch)', 'खिड़की हैंडल (6 इंच)'),
        ('Door Hardware', 'Khirki Handle (8 inch)', 'खिड़की हैंडल (8 इंच)'),
        ('Door Hardware', 'Khirki Handle (9 inch)', 'खिड़की हैंडल (9 इंच)'),
        ('Door Hardware', 'Khirki Handle (10 inch)', 'खिड़की हैंडल (10 इंच)'),
        ('Door Hardware', 'Khirki Handle (12 inch)', 'खिड़की हैंडल (12 इंच)'),
        ('Door Hardware', 'Parda Bracket (Standard)', 'पर्दा ब्रैकेट (Standard)'),
        ('Door Hardware', 'Parda Bracket (Extendable 4-6 inch)', 'पर्दा ब्रैकेट (Extendable 4-6 इंच)'),
        ('Door Hardware', 'Parda Bracket (Extendable 6-10 inch)', 'पर्दा ब्रैकेट (Extendable 6-10 इंच)'),
        ('Paints', 'Readymade Putty (1 Kg)', 'Readymade पुट्टी (1 किलो)'),
        ('Paints', 'Readymade Putty (4 Kg)', 'Readymade पुट्टी (4 किलो)'),
        ('Paints', 'Readymade Putty (10 Kg)', 'Readymade पुट्टी (10 किलो)'),
        ('Paints', 'Readymade Putty (20 Kg)', 'Readymade पुट्टी (20 किलो)'),
        ('Paints', 'Interior Primer (1L)', 'Interior प्राइमर (1L)'),
        ('Paints', 'Interior Primer (4L)', 'Interior प्राइमर (4L)'),
        ('Paints', 'Interior Primer (10L)', 'Interior प्राइमर (10L)'),
        ('Paints', 'Interior Primer (20L)', 'Interior प्राइमर (20L)'),
        ('Paints', 'Exterior Primer (1L)', 'बाहरी प्राइमर (1L)'),
        ('Paints', 'Exterior Primer (4L)', 'बाहरी प्राइमर (4L)'),
        ('Paints', 'Exterior Primer (10L)', 'बाहरी प्राइमर (10L)'),
        ('Paints', 'Exterior Primer (20L)', 'बाहरी प्राइमर (20L)'),
        ('Paints', 'Loha Primer / Red Oxide (1L)', 'लोहा प्राइमर / लाल ऑक्साइड (1L)'),
        ('Paints', 'Loha Primer / Red Oxide (4L)', 'लोहा प्राइमर / लाल ऑक्साइड (4L)'),
        ('Paints', 'Loha Primer / Red Oxide (10L)', 'लोहा प्राइमर / लाल ऑक्साइड (10L)'),
        ('Paints', 'Loha Primer / Red Oxide (20L)', 'लोहा प्राइमर / लाल ऑक्साइड (20L)'),
        ('Paints', 'Pila Primer (1L)', 'पीला प्राइमर (1L)'),
        ('Paints', 'Pila Primer (4L)', 'पीला प्राइमर (4L)'),
        ('Paints', 'Pila Primer (10L)', 'पीला प्राइमर (10L)'),
        ('Paints', 'Pila Primer (20L)', 'पीला प्राइमर (20L)'),
        ('Paints', 'Lakri Primer (1L)', 'लकड़ी प्राइमर (1L)'),
        ('Paints', 'Lakri Primer (4L)', 'लकड़ी प्राइमर (4L)'),
        ('Paints', 'Lakri Primer (10L)', 'लकड़ी प्राइमर (10L)'),
        ('Paints', 'Lakri Primer (20L)', 'लकड़ी प्राइमर (20L)'),
        ('Paints', 'Plastic Paint / Emulsion (50ml)', 'प्लास्टिक पेंट / इमल्शन (50मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (100ml)', 'प्लास्टिक पेंट / इमल्शन (100मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (200ml)', 'प्लास्टिक पेंट / इमल्शन (200मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (500ml)', 'प्लास्टिक पेंट / इमल्शन (500मिली)'),
        ('Paints', 'Plastic Paint / Emulsion (1L)', 'प्लास्टिक पेंट / इमल्शन (1L)'),
        ('Paints', 'Plastic Paint / Emulsion (4L)', 'प्लास्टिक पेंट / इमल्शन (4L)'),
        ('Paints', 'Plastic Paint / Emulsion (10L)', 'प्लास्टिक पेंट / इमल्शन (10L)'),
        ('Paints', 'Plastic Paint / Emulsion (20L)', 'प्लास्टिक पेंट / इमल्शन (20L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (50ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (50मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (100ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (100मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (200ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (200मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (500ml)', 'वेदर प्रूफ पेंट / बाहरी पेंट (500मिली)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (1L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (1L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (4L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (4L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (10L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (10L)'),
        ('Paints', 'Weather Proof Paint / Exterior Paint (20L)', 'वेदर प्रूफ पेंट / बाहरी पेंट (20L)'),
        ('Paints', 'Tel Paint / Enamel Paint (50ml)', 'तेल पेंट / इनेमल पेंट (50मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (100ml)', 'तेल पेंट / इनेमल पेंट (100मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (200ml)', 'तेल पेंट / इनेमल पेंट (200मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (500ml)', 'तेल पेंट / इनेमल पेंट (500मिली)'),
        ('Paints', 'Tel Paint / Enamel Paint (1L)', 'तेल पेंट / इनेमल पेंट (1L)'),
        ('Paints', 'Tel Paint / Enamel Paint (4L)', 'तेल पेंट / इनेमल पेंट (4L)'),
        ('Paints', 'Tel Paint / Enamel Paint (10L)', 'तेल पेंट / इनेमल पेंट (10L)'),
        ('Paints', 'Tel Paint / Enamel Paint (20L)', 'तेल पेंट / इनेमल पेंट (20L)'),
        ('Paints', 'Stainer (50ml)', 'स्टेनर (50मिली)'),
        ('Paints', 'Stainer (100ml)', 'स्टेनर (100मिली)'),
        ('Paints', 'Stainer (200ml)', 'स्टेनर (200मिली)'),
        ('Paints', 'Stainer (500ml)', 'स्टेनर (500मिली)'),
        ('Paints', 'Stainer (1L)', 'स्टेनर (1L)'),
        ('Paints', 'Stainer (4L)', 'स्टेनर (4L)'),
        ('Paints', 'Stainer (10L)', 'स्टेनर (10L)'),
        ('Paints', 'Stainer (20L)', 'स्टेनर (20L)'),
        ('Paints', 'Tarpeen Tel (50ml)', 'तारपीन तेल (50मिली)'),
        ('Paints', 'Tarpeen Tel (100ml)', 'तारपीन तेल (100मिली)'),
        ('Paints', 'Tarpeen Tel (200ml)', 'तारपीन तेल (200मिली)'),
        ('Paints', 'Tarpeen Tel (500ml)', 'तारपीन तेल (500मिली)'),
        ('Paints', 'Tarpeen Tel (1L)', 'तारपीन तेल (1L)'),
        ('Paints', 'Tarpeen Tel (4L)', 'तारपीन तेल (4L)'),
        ('Paints', 'Tarpeen Tel (10L)', 'तारपीन तेल (10L)'),
        ('Paints', 'Tarpeen Tel (20L)', 'तारपीन तेल (20L)'),
        ('Paints', 'NC Thinner (50ml)', 'एनसी थिनर (50मिली)'),
        ('Paints', 'NC Thinner (100ml)', 'एनसी थिनर (100मिली)'),
        ('Paints', 'NC Thinner (200ml)', 'एनसी थिनर (200मिली)'),
        ('Paints', 'NC Thinner (500ml)', 'एनसी थिनर (500मिली)'),
        ('Paints', 'NC Thinner (1L)', 'एनसी थिनर (1L)'),
        ('Paints', 'NC Thinner (4L)', 'एनसी थिनर (4L)'),
        ('Paints', 'NC Thinner (10L)', 'एनसी थिनर (10L)'),
        ('Paints', 'NC Thinner (20L)', 'एनसी थिनर (20L)'),
        ('Paints', 'Varnish / Polish', 'Varnish / पॉलिश'),
        ('Paints', 'Chana Polish / Gala Polish', 'Chana पॉलिश / Gala पॉलिश'),
        ('Paints', 'Roller Brush (50ml)', 'रोलर ब्रश (50मिली)'),
        ('Paints', 'Roller Brush (100ml)', 'रोलर ब्रश (100मिली)'),
        ('Paints', 'Roller Brush (200ml)', 'रोलर ब्रश (200मिली)'),
        ('Paints', 'Roller Brush (500ml)', 'रोलर ब्रश (500मिली)'),
        ('Paints', 'Roller Brush (1L)', 'रोलर ब्रश (1L)'),
        ('Paints', 'Roller Brush (4L)', 'रोलर ब्रश (4L)'),
        ('Paints', 'Roller Brush (10L)', 'रोलर ब्रश (10L)'),
        ('Paints', 'Roller Brush (20L)', 'रोलर ब्रश (20L)'),
        ('Paints', 'Roller Patti (50ml)', 'रोलर पट्टी (50मिली)'),
        ('Paints', 'Roller Patti (100ml)', 'रोलर पट्टी (100मिली)'),
        ('Paints', 'Roller Patti (200ml)', 'रोलर पट्टी (200मिली)'),
        ('Paints', 'Roller Patti (500ml)', 'रोलर पट्टी (500मिली)'),
        ('Paints', 'Roller Patti (1L)', 'रोलर पट्टी (1L)'),
        ('Paints', 'Roller Patti (4L)', 'रोलर पट्टी (4L)'),
        ('Paints', 'Roller Patti (10L)', 'रोलर पट्टी (10L)'),
        ('Paints', 'Roller Patti (20L)', 'रोलर पट्टी (20L)'),
        ('Paints', 'Sorish Kagas / Regmar (#80 Number)', 'सरेस कागज़ / रेगमार (#80 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#120 Number)', 'सरेस कागज़ / रेगमार (#120 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#150 Number)', 'सरेस कागज़ / रेगमार (#150 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#220 Number)', 'सरेस कागज़ / रेगमार (#220 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#320 Number)', 'सरेस कागज़ / रेगमार (#320 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#400 Number)', 'सरेस कागज़ / रेगमार (#400 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#600 Number)', 'सरेस कागज़ / रेगमार (#600 Number)'),
        ('Paints', 'Sorish Kagas / Regmar (#1000 Number)', 'सरेस कागज़ / रेगमार (#1000 Number)'),
        ('Paints', 'Lakri Ka Regmar (#80 Number)', 'लकड़ी का रेगमार (#80 Number)'),
        ('Paints', 'Lakri Ka Regmar (#120 Number)', 'लकड़ी का रेगमार (#120 Number)'),
        ('Paints', 'Lakri Ka Regmar (#150 Number)', 'लकड़ी का रेगमार (#150 Number)'),
        ('Paints', 'Lakri Ka Regmar (#220 Number)', 'लकड़ी का रेगमार (#220 Number)'),
        ('Paints', 'Lakri Ka Regmar (#320 Number)', 'लकड़ी का रेगमार (#320 Number)'),
        ('Paints', 'Lakri Ka Regmar (#400 Number)', 'लकड़ी का रेगमार (#400 Number)'),
        ('Paints', 'Lakri Ka Regmar (#600 Number)', 'लकड़ी का रेगमार (#600 Number)'),
        ('Paints', 'Lakri Ka Regmar (#1000 Number)', 'लकड़ी का रेगमार (#1000 Number)'),
        ('Adhesives', 'Elfi / Fevikwik', 'Elfi / Fevikwik'),
        ('Paints', 'Silicone Gel Tube', 'सिलिकॉन Gel ट्यूब'),
        ('Paints', 'Silicone Gun', 'सिलिकॉन Gun'),
        ('Paints', 'Araldite Paste / Do-Component Gum', 'Araldite Paste / Do-Component गोंद'),
        ('Paints', 'Foam Spray Tube', 'Foam स्प्रे ट्यूब'),
        ('Paints', 'WD-40 / Morcha Saaf Spray', 'WD-40 / Morcha Saaf स्प्रे'),
        ('Paints', 'Regmaal (Grit 80 - Mota)', 'रेगमाल (Grit 80 - Mota)'),
        ('Paints', 'Regmaal (Grit 150 - Madhyam)', 'रेगमाल (Grit 150 - Madhyam)'),
        ('Paints', 'Regmaal (Grit 220 - Baarik)', 'रेगमाल (Grit 220 - Baarik)'),
        ('Paints', 'Geela Regmaal (Grit 400)', 'Geela रेगमाल (Grit 400)'),
        ('Paints', 'Rang Kuchi (1 inch)', 'रंग कूची (1 इंच)'),
        ('Paints', 'Rang Kuchi (2 inch)', 'रंग कूची (2 इंच)'),
        ('Paints', 'Rang Kuchi (3 inch)', 'रंग कूची (3 इंच)'),
        ('Paints', 'Rang Kuchi (4 inch)', 'रंग कूची (4 इंच)'),
        ('Adhesives', 'Masking Tape (0.5 inch)', 'मास्किंग टेप (0.5 इंच)'),
        ('Adhesives', 'Masking Tape (1 inch)', 'मास्किंग टेप (1 इंच)'),
        ('Adhesives', 'Masking Tape (2 inch)', 'मास्किंग टेप (2 इंच)'),
        ('Adhesives', 'Masking Tape (3 inch)', 'मास्किंग टेप (3 इंच)'),
        ('Adhesives', 'Fevicol SH (200 g)', 'फेविकोल एसएच (200 ग्राम)'),
        ('Adhesives', 'Fevicol SH (500 g)', 'फेविकोल एसएच (500 ग्राम)'),
        ('Adhesives', 'Fevicol SH (1 Kg)', 'फेविकोल एसएच (1 किलो)'),
        ('Adhesives', 'Fevicol SH (2 Kg)', 'फेविकोल एसएच (2 किलो)'),
        ('Adhesives', 'Fevicol SH (5 Kg)', 'फेविकोल एसएच (5 किलो)'),
        ('Adhesives', 'Fevicol SH (10 Kg)', 'फेविकोल एसएच (10 किलो)'),
        ('Adhesives', 'Fevicol MR (200 g)', 'फेविकोल एमआर (200 ग्राम)'),
        ('Adhesives', 'Fevicol MR (500 g)', 'फेविकोल एमआर (500 ग्राम)'),
        ('Adhesives', 'Fevicol MR (1 Kg)', 'फेविकोल एमआर (1 किलो)'),
        ('Adhesives', 'Fevicol MR (2 Kg)', 'फेविकोल एमआर (2 किलो)'),
        ('Adhesives', 'Fevicol MR (5 Kg)', 'फेविकोल एमआर (5 किलो)'),
        ('Adhesives', 'Fevicol MR (10 Kg)', 'फेविकोल एमआर (10 किलो)'),
        ('Adhesives', 'Fevicol Marine (200 g)', 'फेविकोल मरीन (200 ग्राम)'),
        ('Adhesives', 'Fevicol Marine (500 g)', 'फेविकोल मरीन (500 ग्राम)'),
        ('Adhesives', 'Fevicol Marine (1 Kg)', 'फेविकोल मरीन (1 किलो)'),
        ('Adhesives', 'Fevicol Marine (2 Kg)', 'फेविकोल मरीन (2 किलो)'),
        ('Adhesives', 'Fevicol Marine (5 Kg)', 'फेविकोल मरीन (5 किलो)'),
        ('Adhesives', 'Fevicol Marine (10 Kg)', 'फेविकोल मरीन (10 किलो)'),
        ('Adhesives', 'Fevicol HeatX (200 g)', 'फेविकोल हीटएक्स (200 ग्राम)'),
        ('Adhesives', 'Fevicol HeatX (500 g)', 'फेविकोल हीटएक्स (500 ग्राम)'),
        ('Adhesives', 'Fevicol HeatX (1 Kg)', 'फेविकोल हीटएक्स (1 किलो)'),
        ('Adhesives', 'Fevicol HeatX (2 Kg)', 'फेविकोल हीटएक्स (2 किलो)'),
        ('Adhesives', 'Fevicol HeatX (5 Kg)', 'फेविकोल हीटएक्स (5 किलो)'),
        ('Adhesives', 'Fevicol HeatX (10 Kg)', 'फेविकोल हीटएक्स (10 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (200 g)', 'फेविकोल फास्ट टैक (200 ग्राम)'),
        ('Adhesives', 'Fevicol Fast Tack (500 g)', 'फेविकोल फास्ट टैक (500 ग्राम)'),
        ('Adhesives', 'Fevicol Fast Tack (1 Kg)', 'फेविकोल फास्ट टैक (1 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (2 Kg)', 'फेविकोल फास्ट टैक (2 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (5 Kg)', 'फेविकोल फास्ट टैक (5 किलो)'),
        ('Adhesives', 'Fevicol Fast Tack (10 Kg)', 'फेविकोल फास्ट टैक (10 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (200 g)', 'फेविकोल नेल फ्री अल्ट्रा (200 ग्राम)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (500 g)', 'फेविकोल नेल फ्री अल्ट्रा (500 ग्राम)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (1 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (1 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (2 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (2 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (5 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (5 किलो)'),
        ('Adhesives', 'Fevicol Nail Free Ultra (10 Kg)', 'फेविकोल नेल फ्री अल्ट्रा (10 किलो)'),
        ('Electrical', 'Bijli Tar (0.75 sq mm)', 'बिजली तार (0.75 sq मिमी)'),
        ('Electrical', 'Bijli Tar (1.0 sq mm)', 'बिजली तार (1.0 sq मिमी)'),
        ('Electrical', 'Bijli Tar (1.5 sq mm)', 'बिजली तार (1.5 sq मिमी)'),
        ('Electrical', 'Bijli Tar (2.5 sq mm)', 'बिजली तार (2.5 sq मिमी)'),
        ('Electrical', 'Bijli Tar (4.0 sq mm)', 'बिजली तार (4.0 sq मिमी)'),
        ('Electrical', 'Bijli Tar (6.0 sq mm)', 'बिजली तार (6.0 sq मिमी)'),
        ('Electrical', 'Lachchhi Tar / Board Tar', 'Lachchhi तार / बोर्ड तार'),
        ('Electrical', 'Submersible Motor Tar', 'Submersible मोटर तार'),
        ('Electrical', 'Conduit Pipe / Chhat Pipe', 'कंड्यूट पाइप / छत पाइप'),
        ('Electrical', 'Spring Pipe / Flexible Pipe', 'स्प्रिंग पाइप / Flexible पाइप'),
        ('Electrical', 'Bijli Pipe Elbow', 'बिजली पाइप एल्बो'),
        ('Electrical', 'Junction Box', 'Junction बॉक्स'),
        ('Electrical', 'Modular Switch', 'मॉड्यूलर स्विच'),
        ('Electrical', 'Modular Socket / Plug Point', 'मॉड्यूलर सॉकेट / प्लग पॉइंट'),
        ('Electrical', 'Modular Board Sheet', 'मॉड्यूलर बोर्ड Sheet'),
        ('Electrical', 'Concealed Board / Board Dibba', 'छुपा हुआ बोर्ड / बोर्ड Dibba'),
        ('Electrical', 'Loha Board Box', 'लोहा बोर्ड बॉक्स'),
        ('Electrical', 'Saada Board / Upar Ka Board', 'Saada बोर्ड / Upar का बोर्ड'),
        ('Electrical', 'Bijli Tape', 'बिजली टेप'),
        ('Electrical', 'MCB Switch', 'एमसीबी स्विच'),
        ('Electrical', 'MCB Box', 'एमसीबी बॉक्स'),
        ('Electrical', 'Main Switch', 'मेन स्विच'),
        ('Electrical', 'Cheeni Mitti Fuse', 'Cheeni Mitti Fuse'),
        ('Electrical', 'LED Bulb / Lattu', 'एलईडी Bulb / Lattu'),
        ('Electrical', 'Tube Light', 'ट्यूब लाइट'),
        ('Electrical', 'Chhat Wali LED Light', 'छत वाली एलईडी लाइट'),
        ('Electrical', 'Pankha / Chhat Pankha', 'पंखा / छत पंखा'),
        ('Electrical', 'Exhaust Pankha', 'Exhaust पंखा'),
        ('Electrical', 'Regulator / Dimmer', 'रेगुलेटर / Dimmer'),
        ('Electrical', 'Holder', 'होल्डर'),
        ('Electrical', 'Angle Holder', 'एंगल होल्डर'),
        ('Electrical', 'Top Plug / 3-Pin Plugg', 'Top प्लग / 3-पिन Plugg'),
        ('Electrical', 'Extension Board', 'Extension बोर्ड'),
        ('Electrical', 'Open Wiring Patti / Casing Channel', 'खुला Wiring पट्टी / Casing चैनल'),
        ('Electrical', 'W-Clip / Conduit Pin', 'W-Clip / कंड्यूट पिन'),
        ('Electrical', 'Modular Dummy / Blank', 'मॉड्यूलर Dummy / Blank'),
        ('Electrical', 'Indicator Switch', 'Indicator स्विच'),
        ('Electrical', 'Bada Regulator', 'बड़ा रेगुलेटर'),
        ('Electrical', 'Telephone Point', 'Telephone पॉइंट'),
        ('Electrical', 'Internet Point', 'Internet पॉइंट'),
        ('Electrical', 'Dish Antina Point', 'Dish Antina पॉइंट'),
        ('Electrical', 'Power Switch (AC/Geyser)', 'पावर स्विच (AC/Geyser)'),
        ('Electrical', 'Power Socket (AC/Geyser)', 'पावर सॉकेट (AC/Geyser)'),
        ('Farmer/Agricultural Tools', 'Phawrah / Kudal', 'Phawrah / कुदाल'),
        ('Farmer/Agricultural Tools', 'Hansua / Kachiya', 'Hansua / Kachiya'),
        ('Farmer/Agricultural Tools', 'Belcha', 'बेलचा'),
        ('Farmer/Agricultural Tools', 'Gainti', 'Gainti'),
        ('Farmer/Agricultural Tools', 'Kulhari', 'Kulhari'),
        ('Farmer/Agricultural Tools', 'Tasla / Ghamela / Tagari', 'तसला / Ghamela / Tagari'),
        ('Farmer/Agricultural Tools', 'Plastic Tasla', 'प्लास्टिक तसला'),
        ('Farmer/Agricultural Tools', 'Rassi / Nylon Rassi', 'रस्सी / नायलॉन रस्सी'),
        ('Farmer/Agricultural Tools', 'Patua Sutli', 'Patua सुतली'),
        ('Handpump (Chapakal) Parts', 'Handpump / Chapakal Set (No. 4)', 'हैंडपंप / चापाकल पूरा सेट (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Silinder (No. 4)', 'हैंडपंप सिलेंडर (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Bucket / Leather (No. 4, 2.5 inch)', 'हैंडपंप बकेट / लेदर (नंबर 4, 2.5 इंच)'),
        ('Handpump (Chapakal) Parts', 'Handpump Bucket / Leather (No. 4, 3 inch)', 'हैंडपंप बकेट / लेदर (नंबर 4, 3 इंच)'),
        ('Handpump (Chapakal) Parts', 'Handpump Valve / Chiriya (No. 4)', 'हैंडपंप वाल्व / चिड़िया (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Valve Weight (No. 4)', 'हैंडपंप वाल्व वेट (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Plunger (No. 4)', 'हैंडपंप प्लंजर (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Piston', 'हैंडपंप पिस्टन'),
        ('Handpump (Chapakal) Parts', 'Handpump Rod / Jod Danda (10 ft, No. 4)', 'हैंडपंप रॉड / जोड़ डंडा (10 फीट, नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Rod / Jod Danda (15 ft, No. 4)', 'हैंडपंप रॉड / जोड़ डंडा (15 फीट, नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Rod / Jod Danda (20 ft, No. 4)', 'हैंडपंप रॉड / जोड़ डंडा (20 फीट, नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Handle (No. 4)', 'हैंडपंप हैंडल (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Handle Pin / Bolt', 'हैंडपंप हैंडल पिन / बोल्ट'),
        ('Handpump (Chapakal) Parts', 'Handpump Topi (No. 4)', 'हैंडपंप टोपी (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Thali (No. 4)', 'हैंडपंप थाली (नंबर 4)'),
        ('Handpump (Chapakal) Parts', 'Handpump Tonti', 'हैंडपंप टोंटी'),
        ('Handpump (Chapakal) Parts', 'Handpump Base Plate', 'हैंडपंप Base Plate'),
        ('Handpump (Chapakal) Parts', 'Handpump Chabutra', 'हैंडपंप चबूतरा'),
        ('Handpump (Chapakal) Parts', 'Handpump Chhanna', 'हैंडपंप छन्ना'),
        ('Handpump (Chapakal) Parts', 'Handpump Chadhai Pipe (1.25 inch)', 'हैंडपंप चढ़ाई पाइप (1.25 इंच)'),
        ('Handpump (Chapakal) Parts', 'Handpump Gasket', 'हैंडपंप गैसकेट'),
        ('Handpump (Chapakal) Parts', 'Handpump Nut-Bolt Set', 'हैंडपंप नट-बोल्ट सेट'),
        ('Handpump (Chapakal) Parts', 'Handpump Marammat Kit', 'हैंडपंप मरम्मत किट'),
        ('Farmer/Agricultural Tools', 'Tullu Motor / Water Pump', 'Tullu मोटर / पानी पंप'),
        ('Farmer/Agricultural Tools', 'Tirpal', 'Tirpal'),
        ('Farmer/Agricultural Tools', 'Dawa Chhirakne Wali Machine', 'Dawa Chhirakne वाली मशीन'),
        ('Farmer/Agricultural Tools', 'Hal', 'हल'),
        ('Farmer/Agricultural Tools', 'Jua', 'जुआ'),
        ('Farmer/Agricultural Tools', 'Hansiya (Chhota)', 'हंसिया (Chhota)'),
        ('Farmer/Agricultural Tools', 'Hasua (Bada)', 'हसुआ (Bada)'),
        ('Farmer/Agricultural Tools', 'Khurpi', 'खुरपी'),
        ('Farmer/Agricultural Tools', 'Kudal (No. 1)', 'कुदाल (नंबर 1)'),
        ('Farmer/Agricultural Tools', 'Kudal (No. 2)', 'कुदाल (नंबर 2)'),
        ('Farmer/Agricultural Tools', 'Belcha / Fawda (No. 6)', 'बेलचा / फावड़ा (नंबर 6)'),
        ('Farmer/Agricultural Tools', 'Belcha / Fawda (No. 8)', 'बेलचा / फावड़ा (नंबर 8)'),
        ('Farmer/Agricultural Tools', 'Gaiti (3 lb)', 'गैंती (3 पाउंड)'),
        ('Farmer/Agricultural Tools', 'Gaiti (5 lb)', 'गैंती (5 पाउंड)'),
        ('Farmer/Agricultural Tools', 'Soop', 'सूप'),
        ('Farmer/Agricultural Tools', 'Tokri', 'टोकरी'),
        ('Farmer/Agricultural Tools', 'Chalni (Baarik/Mota)', 'छलनी (Baarik/Mota)'),
        ('Farmer/Agricultural Tools', 'Spray Pump (16 Ltr)', 'स्प्रे पंप (16 Ltr)'),
        ('Farmer/Agricultural Tools', 'Spray Pump (18 Ltr)', 'स्प्रे पंप (18 Ltr)'),
        ('Farmer/Agricultural Tools', 'Khaad Kaanta', 'खाद कांटा'),
        ('Farmer/Agricultural Tools', 'Saan Patthar', 'सान पत्थर'),
        ('Farmer/Agricultural Tools', 'Daranti', 'दरांती'),
        ('Safety Items', 'Welding Rod / Ranga', 'वेल्डिंग Rod / Ranga'),
        ('Safety Items', 'Welding Kagas / Aina', 'वेल्डिंग कागज़ / आईना'),
        ('Safety Items', 'Safety Cap / Topi', 'सेफ्टी Cap / Topi'),
        ('Safety Items', 'Kapde Ka Hand-Glove', 'Kapde का Hand-Glove'),
        ('Safety Items', 'Rubber Glove', 'Rubber Glove'),
        ('Safety Items', 'Safety Chashma', 'सेफ्टी Chashma'),
        ('Safety Items', 'Mask', 'Mask'),
        ('Measuring/Misc', 'Plastic Lock Tie / Cable Lock', 'प्लास्टिक लॉक / ताला Tie / Cable लॉक / ताला'),
        ('Measuring/Misc', 'Khirki Jali - Loha (0.5 inch, 2 ft)', 'खिड़की जाली - लोहा (0.5 इंच, 2 फीट)'),
        ('Measuring/Misc', 'Khirki Jali - Loha (0.5 inch, 3 ft)', 'खिड़की जाली - लोहा (0.5 इंच, 3 फीट)'),
        ('Measuring/Misc', 'Khirki Jali - Loha (0.5 inch, 4 ft)', 'खिड़की जाली - लोहा (0.5 इंच, 4 फीट)'),
        ('Measuring/Misc', 'Khirki Jali - Loha (1 inch, 2 ft)', 'खिड़की जाली - लोहा (1 इंच, 2 फीट)'),
        ('Measuring/Misc', 'Khirki Jali - Loha (1 inch, 3 ft)', 'खिड़की जाली - लोहा (1 इंच, 3 फीट)'),
        ('Measuring/Misc', 'Khirki Jali - Loha (1 inch, 4 ft)', 'खिड़की जाली - लोहा (1 इंच, 4 फीट)'),
        ('Measuring/Misc', 'Machine Tel / Mobil Oil', 'मशीन तेल / Mobil Oil'),
        ('Measuring/Misc', 'Giriss / Heavy Grease', 'Giriss / भारी ग्रीस'),
        ('Measuring/Misc', 'Lakri Beading / Gola', 'लकड़ी Beading / Gola'),
        ('Measuring/Misc', 'Machine Belt / V-Belt', 'मशीन Belt / V-Belt'),
        ('Measuring/Misc', 'Chakka / Trolley Wheel', 'Chakka / Trolley Wheel'),
        ('Measuring/Misc', 'Loha Junna / Steel Wool', 'लोहा Junna / स्टील Wool'),
        ('Fasteners', 'Pin Kati (0.5 inch)', 'Pin Kati (0.5 इंच)'),
        ('Fasteners', 'Pin Kati (0.75 inch)', 'Pin Kati (0.75 इंच)'),
        ('Fasteners', 'Pin Kati (1 inch)', 'Pin Kati (1 इंच)'),
        ('Fasteners', 'Pin Kati (1.5 inch)', 'Pin Kati (1.5 इंच)'),
        ('Fasteners', 'Pin Kati (2 inch)', 'Pin Kati (2 इंच)'),
        ('Hand Tools', 'Putty Patti (2 inch)', 'Putty Patti (2 inch)'),
        ('Hand Tools', 'Putty Patti (3 inch)', 'Putty Patti (3 inch)'),
        ('Hand Tools', 'Putty Patti (4 inch)', 'Putty Patti (4 inch)'),
        ('Hand Tools', 'Putty Patti (6 inch)', 'Putty Patti (6 inch)'),
        ('Plumbing', 'Check Valve (0.5 inch)', 'चेक वाल्व (0.5 इंच)'),
        ('Plumbing', 'Check Valve (0.75 inch)', 'चेक वाल्व (0.75 इंच)'),
        ('Plumbing', 'Check Valve (1 inch)', 'चेक वाल्व (1 इंच)'),
        ('Plumbing', 'Check Valve (1.25 inch)', 'चेक वाल्व (1.25 इंच)'),
        ('Plumbing', 'Check Valve (1.5 inch)', 'चेक वाल्व (1.5 इंच)'),
        ('Plumbing', 'Check Valve (2 inch)', 'चेक वाल्व (2 इंच)'),
        ('Plumbing', 'Loha Check Valve (0.5 inch)', 'लोहा चेक वाल्व (0.5 इंच)'),
        ('Plumbing', 'Loha Check Valve (0.75 inch)', 'लोहा चेक वाल्व (0.75 इंच)'),
        ('Plumbing', 'Loha Check Valve (1 inch)', 'लोहा चेक वाल्व (1 इंच)'),
        ('Plumbing', 'Loha Check Valve (1.5 inch)', 'लोहा चेक वाल्व (1.5 इंच)'),
        ('Plumbing', 'Loha Check Valve (2 inch)', 'लोहा चेक वाल्व (2 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (0.5 inch)', 'बॉल वाल्व (0.5 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (0.75 inch)', 'बॉल वाल्व (0.75 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (1 inch)', 'बॉल वाल्व (1 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (1.25 inch)', 'बॉल वाल्व (1.25 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (1.5 inch)', 'बॉल वाल्व (1.5 इंच)'),
        ('Plumbing', 'Ball Valve / Chabi (2 inch)', 'बॉल वाल्व (2 इंच)'),
        ('Plumbing', 'Loha Ball Valve (0.5 inch)', 'लोहा बॉल वाल्व (0.5 इंच)'),
        ('Plumbing', 'Loha Ball Valve (0.75 inch)', 'लोहा बॉल वाल्व (0.75 इंच)'),
        ('Plumbing', 'Loha Ball Valve (1 inch)', 'लोहा बॉल वाल्व (1 इंच)'),
        ('Plumbing', 'Loha Ball Valve (1.5 inch)', 'लोहा बॉल वाल्व (1.5 इंच)'),
        ('Plumbing', 'Loha Ball Valve (2 inch)', 'लोहा बॉल वाल्व (2 इंच)'),
        ('Plumbing', 'PVC Ball Valve (0.5 inch)', 'पीवीसी बॉल वाल्व (0.5 इंच)'),
        ('Plumbing', 'PVC Ball Valve (0.75 inch)', 'पीवीसी बॉल वाल्व (0.75 इंच)'),
        ('Plumbing', 'PVC Ball Valve (1 inch)', 'पीवीसी बॉल वाल्व (1 इंच)'),
        ('Plumbing', 'PVC Ball Valve (1.5 inch)', 'पीवीसी बॉल वाल्व (1.5 इंच)'),
        ('Plumbing', 'PVC Ball Valve (2 inch)', 'पीवीसी बॉल वाल्व (2 इंच)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (2 Suta / M6, 1.5 inch)', 'गोल सिर बोल्ट (2 सूता, 1.5 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (2 Suta / M6, 2 inch)', 'गोल सिर बोल्ट (2 सूता, 2 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (2.5 Suta / M8, 2 inch)', 'गोल सिर बोल्ट (2.5 सूता, 2 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (2.5 Suta / M8, 3 inch)', 'गोल सिर बोल्ट (2.5 सूता, 3 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (3 Suta / M10, 3 inch)', 'गोल सिर बोल्ट (3 सूता, 3 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (3 Suta / M10, 4 inch)', 'गोल सिर बोल्ट (3 सूता, 4 inch)'),
        ('Fasteners', 'Carriage Bolt / Gol Sir Bolt (4 Suta / M12, 4 inch)', 'गोल सिर बोल्ट (4 सूता, 4 inch)'),
        ('Farmer/Agricultural Tools', 'Gamla (8 inch)', 'गमला (8 inch)'),
        ('Farmer/Agricultural Tools', 'Gamla (10 inch)', 'गमला (10 inch)'),
        ('Farmer/Agricultural Tools', 'Gamla (12 inch)', 'गमला (12 inch)'),
        ('Farmer/Agricultural Tools', 'Gamla (14 inch)', 'गमला (14 inch)'),
        ('Farmer/Agricultural Tools', 'Gamla (16 inch)', 'गमला (16 inch)'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (10 inch)', 'सीमेंट गमला (10 inch)'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (12 inch)', 'सीमेंट गमला (12 inch)'),
        ('Farmer/Agricultural Tools', 'Cement Gamla (14 inch)', 'सीमेंट गमला (14 inch)'),
        ('Farmer/Agricultural Tools', 'GI Tagari (12 inch)', 'जीआई तगारी (12 inch)'),
        ('Farmer/Agricultural Tools', 'GI Tagari (14 inch)', 'जीआई तगारी (14 inch)'),
        ('Farmer/Agricultural Tools', 'GI Tagari (16 inch)', 'जीआई तगारी (16 inch)'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (12 inch)', 'प्लास्टिक तगारी (12 inch)'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (14 inch)', 'प्लास्टिक तगारी (14 inch)'),
        ('Farmer/Agricultural Tools', 'Plastic Tagari (Non-GI) (16 inch)', 'प्लास्टिक तगारी (16 inch)'),
        ('Door Hardware', 'Link Mortise Lock', 'Link मोर्टिस लॉक'),
        ('Door Hardware', 'Konark Mortise Lock', 'Konark मोर्टिस लॉक'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe (0.75 inch)', 'प्रेशर पाइप (0.75 इंच)'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe (1 inch)', 'प्रेशर पाइप (1 इंच)'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe Jointer (0.75 inch)', 'प्रेशर पाइप जॉइंटर (0.75 इंच)'),
        ('Farmer/Agricultural Tools', 'Pressure Pipe Jointer (1 inch)', 'प्रेशर पाइप जॉइंटर (1 इंच)'),
        ('Door Hardware', 'Koniya (1 inch)', 'कोनिया (1 inch)'),
        ('Door Hardware', 'Koniya (1.5 inch)', 'कोनिया (1.5 inch)'),
        ('Door Hardware', 'Koniya (2 inch)', 'कोनिया (2 inch)'),
        ('Door Hardware', 'Koniya (3 inch)', 'कोनिया (3 inch)'),
        ('Door Hardware', 'Koniya (4 inch)', 'कोनिया (4 inch)'),
        ('Building Materials', 'Kirmichi (1 kg)', 'किरमिची (1 kg)'),
        ('Building Materials', 'Kirmichi (5 kg)', 'किरमिची (5 kg)'),
        ('Building Materials', 'Kirmichi (25 kg)', 'किरमिची (25 kg)'),
        ('Hand Tools', 'Gurmala (9 inch)', 'गुरमाला (9 inch)'),
        ('Hand Tools', 'Gurmala (10 inch)', 'गुरमाला (10 inch)'),
        ('Hand Tools', 'Gurmala (12 inch)', 'गुरमाला (12 inch)'),
        ('Hand Tools', 'Gurmala (14 inch)', 'गुरमाला (14 inch)'),
        ('Building Materials', 'SS Jali Sheet (12x24 inch)', 'स्टेनलेस स्टील जाली शीट (12x24 inch)'),
        ('Building Materials', 'SS Jali Sheet (12x36 inch)', 'स्टेनलेस स्टील जाली शीट (12x36 inch)'),
        ('Building Materials', 'Aluminium Jali Sheet (12x24 inch)', 'एल्युमिनियम जाली शीट (12x24 inch)'),
        ('Building Materials', 'Aluminium Jali Sheet (12x36 inch)', 'एल्युमिनियम जाली शीट (12x36 inch)'),
        ('Building Materials', 'GI Jali Sheet (12x24 inch)', 'जीआई जाली शीट (12x24 inch)'),
        ('Building Materials', 'GI Jali Sheet (12x36 inch)', 'जीआई जाली शीट (12x36 inch)'),
        ('Hand Tools', 'Inchi Tape / Feeta (3m)', 'इंची टेप / फीता (3m)'),
        ('Hand Tools', 'Inchi Tape / Feeta (5m)', 'इंची टेप / फीता (5m)'),
        ('Hand Tools', 'Inchi Tape / Feeta (10m)', 'इंची टेप / फीता (10m)'),
        ('Hand Tools', 'Inchi Tape / Feeta (50m)', 'इंची टेप / फीता (50m)'),
        ('Hand Tools', 'Inchi Tape / Feeta (100m)', 'इंची टेप / फीता (100m)')
    ) AS seed(category_name, name_en, name_hi)
JOIN categories c
  ON LOWER(c.name_en) = LOWER(seed.category_name);

COMMIT;

-- Verification:
-- SELECT COUNT(*) FROM products;
-- SELECT COUNT(DISTINCT category_id) FROM products;
-- SELECT c.name_en, COUNT(*)
-- FROM products p
-- JOIN categories c ON c.id = p.category_id
-- GROUP BY c.name_en
-- ORDER BY c.name_en;
